### MSC_DA_CA2

### Compare: Ireland (IRL)  with New Zealand (NZL), Finland (FIN) or Norway (NOR), Denmark (DNK), Portugal (PRT). 

Ireland's transport infrastructure can be compared to those of other countries in a variety of ways. Here are a few nations that may provide useful comparisons with Ireland in terms of economic growth, size, geography, and urban-rural dynamics:

Consider aspects such as the extent and quality of road and rail networks, investment in public transport, policies towards sustainable transportation, and the difficulty of providing connectivity in both urban and rural areas when comparing Ireland's transport infrastructure to that of these countries. While these countries share certain qualities with Ireland, they also have distinct characteristics due to their varied geographical, economic, and historical circumstances.

#### Dataset 1 : Infrastructure investment Rail and Road / Euro, 2021 

Source: Transport infrastructure investment and maintenance

OECD: Organisation for Economic Co-operation and Development
OECD (2023), Infrastructure investment (indicator). doi: 10.1787/b06ce3ad-en (Accessed on 17 December 2023)
https://data.oecd.org/transport/infrastructure-investment.htm

Infrastructure investment covers spending on new transport construction and the improvement of the existing network. Infrastructure investment is a key determinant of performance in the transport sector. Inland infrastructure includes road, rail, inland waterways, maritime ports and airports and takes account of all sources of financing. Efficient transport infrastructure provides economic and social benefits to both advanced and emerging economies by: improving market accessibility and productivity, ensuring balanced regional economic development, creating employment, promoting labour mobility and connecting communities. This indicator is measured as a share of GDP for total inland investment and in euros for the road, rail, air, inland waterways and sea components.


Definition of Infrastructure investment:

Infrastructure investment covers spending on new transport construction and the improvement of the existing network. Infrastructure investment is a key determinant of performance in the transport sector. Inland infrastructure includes road, rail, inland waterways, maritime ports and airports and takes account of all sources of financing. Efficient transport infrastructure provides economic and social benefits to both advanced and emerging economies by: improving market accessibility and productivity, ensuring balanced regional economic development, creating employment, promoting labour mobility and connecting communities. This indicator is measured as a share of GDP for total inland investment and in euros for the road, rail, air, inland waterways and sea components

     __________________________////__________________________________

#### Dataset 2: Passenger transportRail / Road, Million passenger-kilometres, 2018 – 2021

Source: Passenger transport

https://data.oecd.org/transport/passenger-transport.htm#indicator-chart

Citation: OECD (2023), Passenger transport (indicator). doi: 10.1787/463da4d1-en (Accessed on 17 December 2023)

Passenger transport refers to the total movement of passengers using inland transport on a given network. Data are expressed in million passenger-kilometres, which represents the transport of a passenger for one kilometre. Components for road and rail are available.

Definition of Passenger transport:

Passenger transport refers to the total movement of passengers using inland transport on a given network. Data are expressed in million passenger-kilometres, which represents the transport of a passenger for one kilometre. Components for road and rail are available.

        ________________________________________////___________________________________________
        
#### Dataset 3: Passenger car registrations

https://data.oecd.org/transport/passenger-car-registrations.htm#indicator-chart

Passenger car registrations refer to the number of newly (first-time) registered passenger cars (private cars) or vehicles (commercial cars) registered to the authorities. Data are sourced via the European Automobile Manufacturer's Association (ACEA) and measured in number of units. Data are measured as an index with the base year 2015.

Definition of Passenger car registrations: 

Passenger car registrations refer to the number of newly (first-time) registered passenger cars (private cars) or vehicles (commercial cars) registered to the authorities. Data are sourced via the European Automobile Manufacturer's Association (ACEA) and measured in number of units. Data are measured as an index with the base year 2015.

Citation:
OECD (2023), Passenger car registrations (indicator). doi: 10.1787/c58fcf22-en (Accessed on 17 December 2023)

    _____________________________________________________////____________________________________________
   
#### Dataset 4 : Gross domestic product (GDP)

https://data.oecd.org/gdp/gross-domestic-product-gdp.htm#indicator-chart

Gross domestic product (GDP) is the standard measure of the value added created through the production of goods and services in a country during a certain period. As such, it also measures the income earned from that production, or the total amount spent on final goods and services (less imports). While GDP is the single most important indicator to capture economic activity, it falls short of providing a suitable measure of people's material well-being for which alternative indicators may be more appropriate. This indicator is based on nominal GDP (also called GDP at current prices or GDP in value) and is available in different measures: US dollars and US dollars per capita (current PPPs). All OECD countries compile their data according to the 2008 System of National Accounts (SNA). This indicator is less suited for comparisons over time, as developments are not only caused by real growth, but also by changes in prices and PPPs.

Definition of Gross domestic product (GDP):

Gross domestic product (GDP) is the standard measure of the value added created through the production of goods and services in a country during a certain period. As such, it also measures the income earned from that production, or the total amount spent on final goods and services (less imports). While GDP is the single most important indicator to capture economic activity, it falls short of providing a suitable measure of people's material well-being for which alternative indicators may be more appropriate. This indicator is based on nominal GDP (also called GDP at current prices or GDP in value) and is available in different measures: US dollars and US dollars per capita (current PPPs). All OECD countries compile their data according to the 2008 System of National Accounts (SNA). This indicator is less suited for comparisons over time, as developments are not only caused by real growth, but also by changes in prices and PPPs.

Citation:

OECD (2023), Gross domestic product (GDP) (indicator). doi: 10.1787/dc2f7aec-en (Accessed on 17 December 2023)

In [2]:
#Importing the essential libraries, which are Pandas, Matplotlib, Numpy, and Seaborn.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import style
from matplotlib import cm
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [3]:
#Command to display all columns in the file.
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
# Importing the Dataset 
infra_invest_df= pd.read_csv('infra_invest_transport_rail_road.csv')
infra_invest_df.head()

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUS,INFRAINVEST,RAIL,EUR,A,2018,4.628355e+09,NaN
1,AUS,INFRAINVEST,RAIL,EUR,A,2019,4.935198e+09,NaN
2,AUS,INFRAINVEST,RAIL,EUR,A,2020,5.192725e+09,NaN
3,AUS,INFRAINVEST,RAIL,EUR,A,2021,6.750072e+09,NaN
4,AUS,INFRAINVEST,ROAD,EUR,A,2018,1.436391e+10,NaN

In [152]:
infra_invest_df.shape

(235, 8)

In [153]:
infra_invest_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    235 non-null    object
 1   INDICATOR   235 non-null    object
 2   SUBJECT     235 non-null    object
 3   MEASURE     235 non-null    object
 4   FREQUENCY   235 non-null    object
 5   TIME        235 non-null    int64
 6   Value       231 non-null    float64
 7   Flag Codes  21 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 14.8+ KB

In [154]:
infra_invest_df.dtypes

LOCATION       object
INDICATOR      object
SUBJECT        object
MEASURE        object
FREQUENCY      object
TIME            int64
Value         float64
Flag Codes     object
dtype: object

In [155]:
infra_invest_df.nunique()

LOCATION       35
INDICATOR       1
SUBJECT         2
MEASURE         1
FREQUENCY       1
TIME            4
Value         229
Flag Codes      3
dtype: int64

In [156]:
infra_invest_df.isnull().sum()

LOCATION        0
INDICATOR       0
SUBJECT         0
MEASURE         0
FREQUENCY       0
TIME            0
Value           4
Flag Codes    214
dtype: int64

In [157]:
# Identifying duplicates (change 'keep' to 'first', 'last', or False if appropriate)
duplicates = infra_invest_df.duplicated(keep=False)
print('Duplicates rows:')
print(infra_invest_df[duplicates])

Duplicates rows:
Empty DataFrame
Columns: [LOCATION, INDICATOR, SUBJECT, MEASURE, FREQUENCY, TIME, Value, Flag Codes]
Index: []

In [158]:
# Checking the unique values
unique_locations = infra_invest_df['LOCATION'].unique()
print(unique_locations)

['AUS' 'AUT' 'BEL' 'CAN' 'CZE' 'DNK' 'FIN' 'FRA' 'DEU' 'GRC' 'HUN' 'ISL'
 'IRL' 'ITA' 'JPN' 'KOR' 'LUX' 'MEX' 'NZL' 'NOR' 'POL' 'PRT' 'SVK' 'ESP'
 'SWE' 'CHE' 'TUR' 'GBR' 'USA' 'EST' 'LVA' 'LTU' 'SVN' 'ISR' 'CHL']

In [159]:
# Checking the unique values
unique_period = infra_invest_df['TIME'].unique()
print(unique_period)

[2018 2019 2020 2021]

In [160]:
# Checking the unique values
unique_period = infra_invest_df['SUBJECT'].unique()
print(unique_period)

['RAIL' 'ROAD']

In [161]:
infra_invest_df = infra_invest_df.drop(['Flag Codes', 'FREQUENCY'], axis=1)
infra_invest_df.head()

  LOCATION    INDICATOR SUBJECT MEASURE  TIME         Value
0      AUS  INFRAINVEST    RAIL     EUR  2018  4.628355e+09
1      AUS  INFRAINVEST    RAIL     EUR  2019  4.935198e+09
2      AUS  INFRAINVEST    RAIL     EUR  2020  5.192725e+09
3      AUS  INFRAINVEST    RAIL     EUR  2021  6.750072e+09
4      AUS  INFRAINVEST    ROAD     EUR  2018  1.436391e+10

In [165]:
infra_invest_df.isnull().values.any()

True

In [166]:
infra_invest_df.isnull().sum()

LOCATION     0
INDICATOR    0
SUBJECT      0
MEASURE      0
TIME         0
Value        4
dtype: int64

In [163]:
infra_invest_df.shape

(235, 6)

In [125]:
# Importing the Dataset 
passenger_transport = pd.read_csv('passenger_transport.csv')
passenger_transport.head()

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2018,17157.920674,NaN
1,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2019,17814.174308,NaN
2,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2020,14166.446294,NaN
3,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2021,8845.193462,NaN
4,AUS,PASSTRANSP,ROAD,MLN_PKM,A,2018,304707.073631,NaN

In [126]:
passenger_transport.shape

(218, 8)

In [127]:
passenger_transport.isnull().sum()

LOCATION        0
INDICATOR       0
SUBJECT         0
MEASURE         0
FREQUENCY       0
TIME            0
Value           4
Flag Codes    191
dtype: int64

In [128]:
# Checking the unique values
unique_locations = infra_invest_df['LOCATION'].unique()
print(unique_locations)

['AUS' 'AUT' 'BEL' 'CAN' 'CZE' 'DNK' 'FIN' 'FRA' 'DEU' 'GRC' 'HUN' 'ISL'
 'IRL' 'ITA' 'JPN' 'KOR' 'LUX' 'MEX' 'NZL' 'NOR' 'POL' 'PRT' 'SVK' 'ESP'
 'SWE' 'CHE' 'TUR' 'GBR' 'USA' 'EST' 'LVA' 'LTU' 'SVN' 'ISR' 'CHL']

In [129]:
# Checking the unique values
unique_period = passenger_transport['SUBJECT'].unique()
print(unique_period)

['RAIL' 'ROAD']

In [130]:
passenger_transport = passenger_transport.drop(['Flag Codes', 'FREQUENCY'], axis=1)
passenger_transport.head()

  LOCATION   INDICATOR SUBJECT  MEASURE  TIME          Value
0      AUS  PASSTRANSP    RAIL  MLN_PKM  2018   17157.920674
1      AUS  PASSTRANSP    RAIL  MLN_PKM  2019   17814.174308
2      AUS  PASSTRANSP    RAIL  MLN_PKM  2020   14166.446294
3      AUS  PASSTRANSP    RAIL  MLN_PKM  2021    8845.193462
4      AUS  PASSTRANSP    ROAD  MLN_PKM  2018  304707.073631

In [131]:
passenger_transport.shape

(218, 6)

In [136]:
passenger_transport.isnull().values.any()

True

In [137]:
passenger_transport.isnull().sum()

LOCATION     0
INDICATOR    0
SUBJECT      0
MEASURE      0
TIME         0
Value        4
dtype: int64

In [1]:
# Importing the Dataset 
car_regist = pd.read_csv('passenger_car_registrations.csv')
car_regist.head()

NameError: name 'pd' is not defined

In [ ]:
car_regist.shape

In [199]:
car_regist.isnull().sum()

LOCATION         0
INDICATOR        0
SUBJECT          0
MEASURE          0
FREQUENCY        0
TIME             0
Value            0
Flag Codes    2757
dtype: int64

In [200]:
car_regist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2763 entries, 0 to 2762
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    2763 non-null   object
 1   INDICATOR   2763 non-null   object
 2   SUBJECT     2763 non-null   object
 3   MEASURE     2763 non-null   object
 4   FREQUENCY   2763 non-null   object
 5   TIME        2763 non-null   object
 6   Value       2763 non-null   float64
 7   Flag Codes  6 non-null      object
dtypes: float64(1), object(7)
memory usage: 172.8+ KB

In [201]:
car_regist = car_regist.drop(['FREQUENCY', 'Flag Codes'], axis=1)
car_regist.head()

  LOCATION INDICATOR SUBJECT  MEASURE     TIME       Value
0      AUS   PASSCAR     TOT  IDX2015  2015-01   92.612710
1      AUS   PASSCAR     TOT  IDX2015  2015-02   94.883872
2      AUS   PASSCAR     TOT  IDX2015  2015-03  112.127024
3      AUS   PASSCAR     TOT  IDX2015  2015-04   81.480289
4      AUS   PASSCAR     TOT  IDX2015  2015-05   94.458029

In [202]:
car_regist.isnull().values.any()

False

In [203]:
# Convert 'TIME' column to datetime and extract year and month
car_regist['TIME'] = pd.to_datetime(car_regist['TIME'])
car_regist['YEAR'] = car_regist['TIME'].dt.year
car_regist['MONTH'] = car_regist['TIME'].dt.month

# Optionally, drop the original 'TIME' column if you no longer need it
car_regist.drop('TIME', axis=1, inplace=True)

# Rename the DataFrame
newcar_regist = car_regist

In [204]:
# Renaming and creating a new columns
newcar_regist.rename(columns={'YEAR': 'TIME', 'MONTH': 'MONTH_ID'}, inplace=True)
newcar_regist['MONTH'] = newcar_regist['MONTH_ID'].apply(lambda x: pd.Timestamp(f"2021-{x:02d}-01").strftime('%B'))

# Reordering columns to place 'Value' at the end
newcar_regist = newcar_regist[['LOCATION', 'INDICATOR', 'SUBJECT', 'MEASURE', 'TIME', 'MONTH_ID', 'MONTH', 'Value']]

newcar_regist.head()

  LOCATION INDICATOR SUBJECT  MEASURE  TIME  MONTH_ID     MONTH       Value
0      AUS   PASSCAR     TOT  IDX2015  2015         1   January   92.612710
1      AUS   PASSCAR     TOT  IDX2015  2015         2  February   94.883872
2      AUS   PASSCAR     TOT  IDX2015  2015         3     March  112.127024
3      AUS   PASSCAR     TOT  IDX2015  2015         4     April   81.480289
4      AUS   PASSCAR     TOT  IDX2015  2015         5       May   94.458029

In [132]:
# Importing the Dataset 
GDP_df= pd.read_csv('GDP_data.csv')
GDP_df.head()

  LOCATION INDICATOR SUBJECT  MEASURE FREQUENCY  TIME        Value Flag Codes
0      AUS       GDP     TOT  MLN_USD         A  2018  1326195.638        NaN
1      AUS       GDP     TOT  MLN_USD         A  2019  1341053.276        NaN
2      AUS       GDP     TOT  MLN_USD         A  2020  1436700.137        NaN
3      AUS       GDP     TOT  MLN_USD         A  2021  1611809.807        NaN
4      AUS       GDP     TOT  MLN_USD         A  2022  1804621.816        NaN

In [133]:
GDP_df.shape

(195, 8)

In [123]:
GDP_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    195 non-null    object
 1   INDICATOR   195 non-null    object
 2   SUBJECT     195 non-null    object
 3   MEASURE     195 non-null    object
 4   FREQUENCY   195 non-null    object
 5   TIME        195 non-null    int64
 6   Value       195 non-null    float64
 7   Flag Codes  32 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 12.3+ KB

In [124]:
GDP_df.isnull().sum()

LOCATION        0
INDICATOR       0
SUBJECT         0
MEASURE         0
FREQUENCY       0
TIME            0
Value           0
Flag Codes    163
dtype: int64

In [134]:
GDP_df = GDP_df.drop(['Flag Codes', 'FREQUENCY'], axis=1)
GDP_df.head()

  LOCATION INDICATOR SUBJECT  MEASURE  TIME        Value
0      AUS       GDP     TOT  MLN_USD  2018  1326195.638
1      AUS       GDP     TOT  MLN_USD  2019  1341053.276
2      AUS       GDP     TOT  MLN_USD  2020  1436700.137
3      AUS       GDP     TOT  MLN_USD  2021  1611809.807
4      AUS       GDP     TOT  MLN_USD  2022  1804621.816

In [135]:
GDP_df.isnull().values.any()

False

Create a Dictionary: First, create a dictionary that contains the mapping of country codes to country names. You can manually create this dictionary if it's a one-time task, or you can find a source online and import it.

Automate the Mapping: Use this dictionary to replace the country codes in your dataset with their corresponding names.

In [98]:
import pandas as pd

# Your DataFrame here
# ...

# Dictionary for country code to name mapping
country_mapping = {
    'AUS': 'Australia', 'AUT': 'Austria', 'BEL': 'Belgium', 'CAN': 'Canada', 
    'CZE': 'Czech Republic', 'DNK': 'Denmark', 'FIN': 'Finland', 'FRA': 'France', 
    'DEU': 'Germany', 'GRC': 'Greece', 'HUN': 'Hungary', 'ISL': 'Iceland',
    'IRL': 'Ireland', 'ITA': 'Italy', 'JPN': 'Japan', 'KOR': 'South Korea', 
    'LUX': 'Luxembourg', 'MEX': 'Mexico', 'NZL': 'New Zealand', 'NOR': 'Norway', 
    'POL': 'Poland', 'PRT': 'Portugal', 'SVK': 'Slovakia', 'ESP': 'Spain',
    'SWE': 'Sweden', 'CHE': 'Switzerland', 'TUR': 'Turkey', 'GBR': 'United Kingdom', 
    'USA': 'United States', 'EST': 'Estonia', 'LVA': 'Latvia', 'LTU': 'Lithuania', 
    'SVN': 'Slovenia', 'ISR': 'Israel', 'CHL': 'Chile'
}

# Replace the country codes with names in the DataFrame
df['LOCATION'] = df['LOCATION'].map(country_mapping)

# Display the updated DataFrame
print(df)

NameError: name 'df' is not defined