### MSC_DA_CA2

### Compare: Ireland (IRL)  with New Zealand (NZL), Finland (FIN) or Norway (NOR), Denmark (DNK), Portugal (PRT). 

Ireland's transport infrastructure can be compared to those of other countries in a variety of ways. Here are a few nations that may provide useful comparisons with Ireland in terms of economic growth, size, geography, and urban-rural dynamics:

Consider aspects such as the extent and quality of road and rail networks, investment in public transport, policies towards sustainable transportation, and the difficulty of providing connectivity in both urban and rural areas when comparing Ireland's transport infrastructure to that of these countries. While these countries share certain qualities with Ireland, they also have distinct characteristics due to their varied geographical, economic, and historical circumstances.

#### Dataset 1 : Infrastructure investment Rail and Road / Euro, 2021 

Source: Transport infrastructure investment and maintenance

OECD: Organisation for Economic Co-operation and Development
OECD (2023), Infrastructure investment (indicator). doi: 10.1787/b06ce3ad-en (Accessed on 17 December 2023)
https://data.oecd.org/transport/infrastructure-investment.htm

Infrastructure investment covers spending on new transport construction and the improvement of the existing network. Infrastructure investment is a key determinant of performance in the transport sector. Inland infrastructure includes road, rail, inland waterways, maritime ports and airports and takes account of all sources of financing. Efficient transport infrastructure provides economic and social benefits to both advanced and emerging economies by: improving market accessibility and productivity, ensuring balanced regional economic development, creating employment, promoting labour mobility and connecting communities. This indicator is measured as a share of GDP for total inland investment and in euros for the road, rail, air, inland waterways and sea components.


Definition of Infrastructure investment:

Infrastructure investment covers spending on new transport construction and the improvement of the existing network. Infrastructure investment is a key determinant of performance in the transport sector. Inland infrastructure includes road, rail, inland waterways, maritime ports and airports and takes account of all sources of financing. Efficient transport infrastructure provides economic and social benefits to both advanced and emerging economies by: improving market accessibility and productivity, ensuring balanced regional economic development, creating employment, promoting labour mobility and connecting communities. This indicator is measured as a share of GDP for total inland investment and in euros for the road, rail, air, inland waterways and sea components

     __________________________////__________________________________

#### Dataset 2: Passenger transport Rail / Road, Million passenger-kilometres, 2018 – 2021

Source: Passenger transport

https://data.oecd.org/transport/passenger-transport.htm#indicator-chart

Citation: OECD (2023), Passenger transport (indicator). doi: 10.1787/463da4d1-en (Accessed on 17 December 2023)

Passenger transport refers to the total movement of passengers using inland transport on a given network. Data are expressed in million passenger-kilometres, which represents the transport of a passenger for one kilometre. Components for road and rail are available.

Definition of Passenger transport:

Passenger transport refers to the total movement of passengers using inland transport on a given network. Data are expressed in million passenger-kilometres, which represents the transport of a passenger for one kilometre. Components for road and rail are available.

        ________________________________________////___________________________________________
        
#### Dataset 3: Passenger car registrations

https://data.oecd.org/transport/passenger-car-registrations.htm#indicator-chart

Passenger car registrations refer to the number of newly (first-time) registered passenger cars (private cars) or vehicles (commercial cars) registered to the authorities. Data are sourced via the European Automobile Manufacturer's Association (ACEA) and measured in number of units. Data are measured as an index with the base year 2015.

Definition of Passenger car registrations: 

Passenger car registrations refer to the number of newly (first-time) registered passenger cars (private cars) or vehicles (commercial cars) registered to the authorities. Data are sourced via the European Automobile Manufacturer's Association (ACEA) and measured in number of units. Data are measured as an index with the base year 2015.

Citation:
OECD (2023), Passenger car registrations (indicator). doi: 10.1787/c58fcf22-en (Accessed on 17 December 2023)

    _____________________________________________________////____________________________________________
   
#### Dataset 4 : Gross domestic product (GDP)

https://data.oecd.org/gdp/gross-domestic-product-gdp.htm#indicator-chart

Gross domestic product (GDP) is the standard measure of the value added created through the production of goods and services in a country during a certain period. As such, it also measures the income earned from that production, or the total amount spent on final goods and services (less imports). While GDP is the single most important indicator to capture economic activity, it falls short of providing a suitable measure of people's material well-being for which alternative indicators may be more appropriate. This indicator is based on nominal GDP (also called GDP at current prices or GDP in value) and is available in different measures: US dollars and US dollars per capita (current PPPs). All OECD countries compile their data according to the 2008 System of National Accounts (SNA). This indicator is less suited for comparisons over time, as developments are not only caused by real growth, but also by changes in prices and PPPs.

Definition of Gross domestic product (GDP):

Gross domestic product (GDP) is the standard measure of the value added created through the production of goods and services in a country during a certain period. As such, it also measures the income earned from that production, or the total amount spent on final goods and services (less imports). While GDP is the single most important indicator to capture economic activity, it falls short of providing a suitable measure of people's material well-being for which alternative indicators may be more appropriate. This indicator is based on nominal GDP (also called GDP at current prices or GDP in value) and is available in different measures: US dollars and US dollars per capita (current PPPs). All OECD countries compile their data according to the 2008 System of National Accounts (SNA). This indicator is less suited for comparisons over time, as developments are not only caused by real growth, but also by changes in prices and PPPs.

Citation:

OECD (2023), Gross domestic product (GDP) (indicator). doi: 10.1787/dc2f7aec-en (Accessed on 17 December 2023)

In [1]:
#Importing the essential libraries, which are Pandas, Matplotlib, Numpy, and Seaborn.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import style
from matplotlib import cm
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
#Command to display all columns in the file.
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#### Dataset - 1

In [3]:
# Importing the Dataset 
infra_invest_df= pd.read_csv('infra_invest_transport_rail_road.csv')
infra_invest_df.head()

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUS,INFRAINVEST,RAIL,EUR,A,2018,4.628355e+09,NaN
1,AUS,INFRAINVEST,RAIL,EUR,A,2019,4.935198e+09,NaN
2,AUS,INFRAINVEST,RAIL,EUR,A,2020,5.192725e+09,NaN
3,AUS,INFRAINVEST,RAIL,EUR,A,2021,6.750072e+09,NaN
4,AUS,INFRAINVEST,ROAD,EUR,A,2018,1.436391e+10,NaN

In [4]:
infra_invest_df.shape

(235, 8)

In [5]:
infra_invest_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    235 non-null    object
 1   INDICATOR   235 non-null    object
 2   SUBJECT     235 non-null    object
 3   MEASURE     235 non-null    object
 4   FREQUENCY   235 non-null    object
 5   TIME        235 non-null    int64
 6   Value       231 non-null    float64
 7   Flag Codes  21 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 14.8+ KB

In [6]:
infra_invest_df.dtypes

LOCATION       object
INDICATOR      object
SUBJECT        object
MEASURE        object
FREQUENCY      object
TIME            int64
Value         float64
Flag Codes     object
dtype: object

In [7]:
infra_invest_df.nunique()

LOCATION       35
INDICATOR       1
SUBJECT         2
MEASURE         1
FREQUENCY       1
TIME            4
Value         229
Flag Codes      3
dtype: int64

In [8]:
infra_invest_df.isnull().sum()

LOCATION        0
INDICATOR       0
SUBJECT         0
MEASURE         0
FREQUENCY       0
TIME            0
Value           4
Flag Codes    214
dtype: int64

In [9]:
# Identifying duplicates (Keep to False)
duplicates = infra_invest_df.duplicated(keep=False)
print('Duplicates rows:')
print(infra_invest_df[duplicates])

Duplicates rows:
Empty DataFrame
Columns: [LOCATION, INDICATOR, SUBJECT, MEASURE, FREQUENCY, TIME, Value, Flag Codes]
Index: []

In [10]:
# Drop the columns
infra_invest_df = infra_invest_df.drop(['Flag Codes', 'FREQUENCY'], axis=1)

# Rename columns
infra_invest_df = infra_invest_df.rename(columns={'LOCATION': 'COUNTRY', 'TIME': 'YEAR', 'Value': 'VALUE_INFRAINVEST'})

infra_invest_df.head()

  COUNTRY    INDICATOR SUBJECT MEASURE  YEAR  VALUE_INFRAINVEST
0     AUS  INFRAINVEST    RAIL     EUR  2018       4.628355e+09
1     AUS  INFRAINVEST    RAIL     EUR  2019       4.935198e+09
2     AUS  INFRAINVEST    RAIL     EUR  2020       5.192725e+09
3     AUS  INFRAINVEST    RAIL     EUR  2021       6.750072e+09
4     AUS  INFRAINVEST    ROAD     EUR  2018       1.436391e+10

In [11]:
infra_invest_df.isnull().values.any()

True

In [12]:
infra_invest_df.isnull().sum()

COUNTRY              0
INDICATOR            0
SUBJECT              0
MEASURE              0
YEAR                 0
VALUE_INFRAINVEST    4
dtype: int64

In [13]:
# Displaying only rows with missing values in 'Value' column 
missing_value_rows = infra_invest_df[infra_invest_df['VALUE_INFRAINVEST'].isnull()]

print(missing_value_rows)

   COUNTRY    INDICATOR SUBJECT MEASURE  YEAR  VALUE_INFRAINVEST
78     ISL  INFRAINVEST    RAIL     EUR  2018                NaN
79     ISL  INFRAINVEST    RAIL     EUR  2019                NaN
80     ISL  INFRAINVEST    RAIL     EUR  2020                NaN
81     ISL  INFRAINVEST    RAIL     EUR  2021                NaN

The missing values in the 'Value' column constitute approximately 1.70% of the total dataset. This is a relatively small percentage and occurs in locations that are not included in the study; in this situation, the simple method such as `dropna` will be used to deal with these missing values.

In [14]:
# Drop rows with missing values in the 'Value' column and rename the DataFrame
newinfra_invest_df = infra_invest_df.dropna(subset=['VALUE_INFRAINVEST'])

# Display the new DataFrame
newinfra_invest_df.head(2)

  COUNTRY    INDICATOR SUBJECT MEASURE  YEAR  VALUE_INFRAINVEST
0     AUS  INFRAINVEST    RAIL     EUR  2018       4.628355e+09
1     AUS  INFRAINVEST    RAIL     EUR  2019       4.935198e+09

In [15]:
newinfra_invest_df.shape

(231, 6)

In [16]:
newinfra_invest_df.isnull().values.any()

False

    ___________________________/////___________________________
#### Dataset - 2

In [17]:
# Importing the Dataset 
passenger_transp = pd.read_csv('passenger_transport.csv')
passenger_transp.head()

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2018,17157.920674,NaN
1,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2019,17814.174308,NaN
2,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2020,14166.446294,NaN
3,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2021,8845.193462,NaN
4,AUS,PASSTRANSP,ROAD,MLN_PKM,A,2018,304707.073631,NaN

In [18]:
passenger_transp.shape

(218, 8)

In [19]:
passenger_transp.isnull().sum()

LOCATION        0
INDICATOR       0
SUBJECT         0
MEASURE         0
FREQUENCY       0
TIME            0
Value           4
Flag Codes    191
dtype: int64

In [20]:
# Drop Columns
passenger_transp = passenger_transp.drop(['Flag Codes', 'FREQUENCY'], axis=1)

# Rename columns
passenger_transp = passenger_transp.rename(columns={'LOCATION': 'COUNTRY', 'TIME': 'YEAR', 'Value': 'VALUE_PASSTRANSP'})

passenger_transp.head()

  COUNTRY   INDICATOR SUBJECT  MEASURE  YEAR  VALUE_PASSTRANSP
0     AUS  PASSTRANSP    RAIL  MLN_PKM  2018      17157.920674
1     AUS  PASSTRANSP    RAIL  MLN_PKM  2019      17814.174308
2     AUS  PASSTRANSP    RAIL  MLN_PKM  2020      14166.446294
3     AUS  PASSTRANSP    RAIL  MLN_PKM  2021       8845.193462
4     AUS  PASSTRANSP    ROAD  MLN_PKM  2018     304707.073631

In [21]:
passenger_transp.shape

(218, 6)

In [22]:
passenger_transp.isnull().values.any()

True

In [23]:
passenger_transp.isnull().sum()

COUNTRY             0
INDICATOR           0
SUBJECT             0
MEASURE             0
YEAR                0
VALUE_PASSTRANSP    4
dtype: int64

In [24]:
# Displaying only rows with missing values in 'Value' column 
missing_value_rows = passenger_transp[passenger_transp['VALUE_PASSTRANSP'].isnull()]

print(missing_value_rows)

   COUNTRY   INDICATOR SUBJECT  MEASURE  YEAR  VALUE_PASSTRANSP
65     ISL  PASSTRANSP    RAIL  MLN_PKM  2018               NaN
66     ISL  PASSTRANSP    RAIL  MLN_PKM  2019               NaN
67     ISL  PASSTRANSP    RAIL  MLN_PKM  2020               NaN
68     ISL  PASSTRANSP    RAIL  MLN_PKM  2021               NaN

The method `dropna` will be used to deal with these missing values for the same reason that the infra_invest_df dataset was justified.

In [25]:
# Drop rows with missing values in the 'Value' column and rename the DataFrame
newpassenger_transp = passenger_transp.dropna(subset=['VALUE_PASSTRANSP'])

# Display the new DataFrame
newpassenger_transp.head(2)

  COUNTRY   INDICATOR SUBJECT  MEASURE  YEAR  VALUE_PASSTRANSP
0     AUS  PASSTRANSP    RAIL  MLN_PKM  2018      17157.920674
1     AUS  PASSTRANSP    RAIL  MLN_PKM  2019      17814.174308

In [26]:
newpassenger_transp.isnull().values.any()

False

    ___________________________/////___________________________
#### Dataset - 3

In [27]:
# Importing the Dataset 
car_regist = pd.read_csv('passenger_car_registrations.csv')
car_regist.head()

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUS,PASSCAR,TOT,IDX2015,M,2015-01,92.612710,NaN
1,AUS,PASSCAR,TOT,IDX2015,M,2015-02,94.883872,NaN
2,AUS,PASSCAR,TOT,IDX2015,M,2015-03,112.127024,NaN
3,AUS,PASSCAR,TOT,IDX2015,M,2015-04,81.480289,NaN
4,AUS,PASSCAR,TOT,IDX2015,M,2015-05,94.458029,NaN

In [28]:
car_regist.shape

(2763, 8)

In [29]:
car_regist.isnull().sum()

LOCATION         0
INDICATOR        0
SUBJECT          0
MEASURE          0
FREQUENCY        0
TIME             0
Value            0
Flag Codes    2757
dtype: int64

In [30]:
car_regist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2763 entries, 0 to 2762
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    2763 non-null   object
 1   INDICATOR   2763 non-null   object
 2   SUBJECT     2763 non-null   object
 3   MEASURE     2763 non-null   object
 4   FREQUENCY   2763 non-null   object
 5   TIME        2763 non-null   object
 6   Value       2763 non-null   float64
 7   Flag Codes  6 non-null      object
dtypes: float64(1), object(7)
memory usage: 172.8+ KB

In [31]:
#Drop Columns
car_regist = car_regist.drop(['FREQUENCY', 'Flag Codes'], axis=1)

# Rename columns
car_regist = car_regist.rename(columns={'LOCATION': 'COUNTRY', 'TIME': 'YEAR', 'Value': 'VALUE_PASSCAR'})

car_regist.head()

  COUNTRY INDICATOR SUBJECT  MEASURE     YEAR  VALUE_PASSCAR
0     AUS   PASSCAR     TOT  IDX2015  2015-01      92.612710
1     AUS   PASSCAR     TOT  IDX2015  2015-02      94.883872
2     AUS   PASSCAR     TOT  IDX2015  2015-03     112.127024
3     AUS   PASSCAR     TOT  IDX2015  2015-04      81.480289
4     AUS   PASSCAR     TOT  IDX2015  2015-05      94.458029

In [32]:
# Extract the year from the 'TIME' column and convert it to int64
car_regist['YEAR'] = car_regist['YEAR'].str.split('-').str[0].astype('int64')

# Renaming the DataFrame
newcar_regist = car_regist

# Display the new DataFrame, where the 'TIME' column only contains the year as an integer
newcar_regist.head()

  COUNTRY INDICATOR SUBJECT  MEASURE  YEAR  VALUE_PASSCAR
0     AUS   PASSCAR     TOT  IDX2015  2015      92.612710
1     AUS   PASSCAR     TOT  IDX2015  2015      94.883872
2     AUS   PASSCAR     TOT  IDX2015  2015     112.127024
3     AUS   PASSCAR     TOT  IDX2015  2015      81.480289
4     AUS   PASSCAR     TOT  IDX2015  2015      94.458029

The aggregation of passenger car registration data by averaging index values was chosen because it best reflects the annual trend of car registrations relative to the base year of 2015. This approach is consistent with traditional statistical practices and correlates with the indexed structure of the data by providing a clear, annual comparative indicator, which is critical for analysing year-over-year trends.

In [33]:
# Average the index 'Value' for each combination of 'LOCATION', 'INDICATOR', 'SUBJECT', 'MEASURE', and 'TIME'
newcar2_regist = newcar_regist.groupby(['COUNTRY', 'INDICATOR', 'SUBJECT', 'MEASURE', 'YEAR']).agg({'VALUE_PASSCAR': 'mean'}).reset_index()

# Checking the aggregated data
newcar2_regist.head()

  COUNTRY INDICATOR SUBJECT  MEASURE  YEAR  VALUE_PASSCAR
0     AUS   PASSCAR     TOT  IDX2015  2015     100.000000
1     AUS   PASSCAR     TOT  IDX2015  2016      94.293781
2     AUS   PASSCAR     TOT  IDX2015  2017      87.265239
3     AUS   PASSCAR     TOT  IDX2015  2018      73.393150
4     AUS   PASSCAR     TOT  IDX2015  2019      61.564372

In [34]:
newcar2_regist.dtypes

COUNTRY           object
INDICATOR         object
SUBJECT           object
MEASURE           object
YEAR               int64
VALUE_PASSCAR    float64
dtype: object

In [35]:
newcar2_regist.shape

(231, 6)

In [36]:
newcar2_regist.isnull().values.any()

False

    ___________________________/////___________________________
#### Dataset - 4

In [37]:
# Importing the Dataset 
GDP_df= pd.read_csv('GDP_data.csv')
GDP_df.head()

  LOCATION INDICATOR SUBJECT  MEASURE FREQUENCY  TIME        Value Flag Codes
0      AUS       GDP     TOT  MLN_USD         A  2018  1326195.638        NaN
1      AUS       GDP     TOT  MLN_USD         A  2019  1341053.276        NaN
2      AUS       GDP     TOT  MLN_USD         A  2020  1436700.137        NaN
3      AUS       GDP     TOT  MLN_USD         A  2021  1611809.807        NaN
4      AUS       GDP     TOT  MLN_USD         A  2022  1804621.816        NaN

In [38]:
GDP_df.shape

(195, 8)

In [39]:
GDP_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    195 non-null    object
 1   INDICATOR   195 non-null    object
 2   SUBJECT     195 non-null    object
 3   MEASURE     195 non-null    object
 4   FREQUENCY   195 non-null    object
 5   TIME        195 non-null    int64
 6   Value       195 non-null    float64
 7   Flag Codes  32 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 12.3+ KB

In [40]:
GDP_df.isnull().sum()

LOCATION        0
INDICATOR       0
SUBJECT         0
MEASURE         0
FREQUENCY       0
TIME            0
Value           0
Flag Codes    163
dtype: int64

In [41]:
# Drop the columns and rename the DataFrame
newgdp_df = GDP_df.drop(['Flag Codes', 'FREQUENCY'], axis=1)

# Rename columns
newgdp_df = newgdp_df.rename(columns={'LOCATION': 'COUNTRY', 'TIME': 'YEAR', 'Value': 'VALUE_GDP'})

newgdp_df.head()

  COUNTRY INDICATOR SUBJECT  MEASURE  YEAR    VALUE_GDP
0     AUS       GDP     TOT  MLN_USD  2018  1326195.638
1     AUS       GDP     TOT  MLN_USD  2019  1341053.276
2     AUS       GDP     TOT  MLN_USD  2020  1436700.137
3     AUS       GDP     TOT  MLN_USD  2021  1611809.807
4     AUS       GDP     TOT  MLN_USD  2022  1804621.816

In [42]:
newgdp_df.shape

(195, 6)

In [43]:
newgdp_df.isnull().values.any()

False

The transformed dataset is now properly formatted for analytical purposes, or the datasets can be combined if necessary. The renaming, dropping, and reordering of columns, as well as the transformation of numerical month data into descriptive labels, improve the dataset's readability. This stage is critical in data analysis because it ensures that the dataset is in the best possible structure for extracting valuable insights and supporting effective data-driven decision-making processes in transportation research.

#### Display all the datasets after transformed

In [44]:
newinfra_invest_df.head(2)

  COUNTRY    INDICATOR SUBJECT MEASURE  YEAR  VALUE_INFRAINVEST
0     AUS  INFRAINVEST    RAIL     EUR  2018       4.628355e+09
1     AUS  INFRAINVEST    RAIL     EUR  2019       4.935198e+09

In [45]:
newinfra_invest_df.shape

(231, 6)

In [46]:
newinfra_invest_df.dtypes

COUNTRY               object
INDICATOR             object
SUBJECT               object
MEASURE               object
YEAR                   int64
VALUE_INFRAINVEST    float64
dtype: object

In [47]:
newpassenger_transp.head(2)

  COUNTRY   INDICATOR SUBJECT  MEASURE  YEAR  VALUE_PASSTRANSP
0     AUS  PASSTRANSP    RAIL  MLN_PKM  2018      17157.920674
1     AUS  PASSTRANSP    RAIL  MLN_PKM  2019      17814.174308

In [48]:
newpassenger_transp.shape

(214, 6)

In [49]:
newpassenger_transp.dtypes

COUNTRY              object
INDICATOR            object
SUBJECT              object
MEASURE              object
YEAR                  int64
VALUE_PASSTRANSP    float64
dtype: object

In [72]:
newgdp_df.head

<bound method NDFrame.head of     COUNTRY INDICATOR SUBJECT  MEASURE  YEAR     VALUE_GDP
0       AUS       GDP     TOT  MLN_USD  2018  1.326196e+06
1       AUS       GDP     TOT  MLN_USD  2019  1.341053e+06
2       AUS       GDP     TOT  MLN_USD  2020  1.436700e+06
3       AUS       GDP     TOT  MLN_USD  2021  1.611810e+06
4       AUS       GDP     TOT  MLN_USD  2022  1.804622e+06
5       AUT       GDP     TOT  MLN_USD  2018  5.033614e+05
6       AUT       GDP     TOT  MLN_USD  2019  5.301392e+05
7       AUT       GDP     TOT  MLN_USD  2020  5.103616e+05
8       AUT       GDP     TOT  MLN_USD  2021  5.358150e+05
9       AUT       GDP     TOT  MLN_USD  2022  6.137149e+05
10      BEL       GDP     TOT  MLN_USD  2018  6.002699e+05
11      BEL       GDP     TOT  MLN_USD  2019  6.411405e+05
12      BEL       GDP     TOT  MLN_USD  2020  6.309210e+05
13      BEL       GDP     TOT  MLN_USD  2021  6.894791e+05
14      BEL       GDP     TOT  MLN_USD  2022  7.651693e+05
15      CAN       GDP     TOT  MLN_USD  2018  1.852988e+06
16      CAN       GDP     TOT  MLN_USD  2019  1.873760e+06
17      CAN       GDP     TOT  MLN_USD  2020  1.794940e+06
18      CAN       GDP     TOT  MLN_USD  2021  2.026899e+06
19      CAN       GDP     TOT  MLN_USD  2022  2.271469e+06
20      CZE       GDP     TOT  MLN_USD  2018  4.373559e+05
21      CZE       GDP     TOT  MLN_USD  2019  4.718327e+05
22      CZE       GDP     TOT  MLN_USD  2020  4.581578e+05
23      CZE       GDP     TOT  MLN_USD  2021  4.793788e+05
24      CZE       GDP     TOT  MLN_USD  2022  5.250144e+05
25      DNK       GDP     TOT  MLN_USD  2018  3.330354e+05
26      DNK       GDP     TOT  MLN_USD  2019  3.483459e+05
27      DNK       GDP     TOT  MLN_USD  2020  3.542778e+05
28      DNK       GDP     TOT  MLN_USD  2021  3.870532e+05
29      DNK       GDP     TOT  MLN_USD  2022  4.421197e+05
30      FIN       GDP     TOT  MLN_USD  2018  2.734560e+05
31      FIN       GDP     TOT  MLN_USD  2019  2.860829e+05
32      FIN       GDP     TOT  MLN_USD  2020  2.892243e+05
33      FIN       GDP     TOT  MLN_USD  2021  3.035274e+05
34      FIN       GDP     TOT  MLN_USD  2022  3.304223e+05
35      FRA       GDP     TOT  MLN_USD  2018  3.125380e+06
36      FRA       GDP     TOT  MLN_USD  2019  3.403159e+06
37      FRA       GDP     TOT  MLN_USD  2020  3.262896e+06
38      FRA       GDP     TOT  MLN_USD  2021  3.481611e+06
39      FRA       GDP     TOT  MLN_USD  2022  3.764759e+06
40      DEU       GDP     TOT  MLN_USD  2018  4.576057e+06
41      DEU       GDP     TOT  MLN_USD  2019  4.770495e+06
42      DEU       GDP     TOT  MLN_USD  2020  4.694786e+06
43      DEU       GDP     TOT  MLN_USD  2021  4.913166e+06
44      DEU       GDP     TOT  MLN_USD  2022  5.323008e+06
45      GRC       GDP     TOT  MLN_USD  2018  3.178815e+05
46      GRC       GDP     TOT  MLN_USD  2019  3.340336e+05
47      GRC       GDP     TOT  MLN_USD  2020  3.032996e+05
48      GRC       GDP     TOT  MLN_USD  2021  3.326953e+05
49      GRC       GDP     TOT  MLN_USD  2022  3.865789e+05
50      HUN       GDP     TOT  MLN_USD  2018  3.119271e+05
51      HUN       GDP     TOT  MLN_USD  2019  3.385267e+05
52      HUN       GDP     TOT  MLN_USD  2020  3.331618e+05
53      HUN       GDP     TOT  MLN_USD  2021  3.567017e+05
54      HUN       GDP     TOT  MLN_USD  2022  4.025096e+05
55      ISL       GDP     TOT  MLN_USD  2018  2.017485e+04
56      ISL       GDP     TOT  MLN_USD  2019  2.150788e+04
57      ISL       GDP     TOT  MLN_USD  2020  1.991209e+04
58      ISL       GDP     TOT  MLN_USD  2021  2.171567e+04
59      ISL       GDP     TOT  MLN_USD  2022  2.659333e+04
60      IRL       GDP     TOT  MLN_USD  2018  4.133241e+05
61      IRL       GDP     TOT  MLN_USD  2019  4.422593e+05
62      IRL       GDP     TOT  MLN_USD  2020  4.713711e+05
63      IRL       GDP     TOT  MLN_USD  2021  5.461841e+05
64      IRL       GDP     TOT  MLN_USD  2022  6.503163e+05
65      ITA       GDP     TOT  MLN_USD  2018  2.600327e+06
66      ITA       GDP     TOT  MLN_USD  2019  2.735577e+06
67      ITA       GDP     TOT  MLN_USD  2020  2.564795e+06
68      ITA       GDP     TOT  MLN_USD  2021  2.814257e+06
69      ITA       GDP     TOT  MLN_USD  2022  3.112291e+06
70      JPN       GDP     TOT  MLN_USD  2018  5.344061e+06
71      JPN       GDP     TOT  MLN_USD  2019  5.352899e+06
72      JPN       GDP     TOT  MLN_USD  2020  5.263053e+06
73      JPN       GDP     TOT  MLN_USD  2021  5.383427e+06
74      JPN       GDP     TOT  MLN_USD  2022  5.703678e+06
75      KOR       GDP     TOT  MLN_USD  2018  2.220442e+06
76      KOR       GDP     TOT  MLN_USD  2019  2.247127e+06
77      KOR       GDP     TOT  MLN_USD  2020  2.316807e+06
78      KOR       GDP     TOT  MLN_USD  2021  2.435556e+06
79      KOR       GDP     TOT  MLN_USD  2022  2.598471e+06
80      LUX       GDP     TOT  MLN_USD  2018  7.082528e+04
81      LUX       GDP     TOT  MLN_USD  2019  7.418482e+04
82      LUX       GDP     TOT  MLN_USD  2020  7.535689e+04
83      LUX       GDP     TOT  MLN_USD  2021  8.425210e+04
84      LUX       GDP     TOT  MLN_USD  2022  9.183705e+04
85      MEX       GDP     TOT  MLN_USD  2018  2.606266e+06
86      MEX       GDP     TOT  MLN_USD  2019  2.601929e+06
87      MEX       GDP     TOT  MLN_USD  2020  2.398621e+06
88      MEX       GDP     TOT  MLN_USD  2021  2.559092e+06
89      MEX       GDP     TOT  MLN_USD  2022  2.838207e+06
90      NLD       GDP     TOT  MLN_USD  2018  9.964473e+05
91      NLD       GDP     TOT  MLN_USD  2019  1.044308e+06
92      NLD       GDP     TOT  MLN_USD  2020  1.043403e+06
93      NLD       GDP     TOT  MLN_USD  2021  1.130685e+06
94      NLD       GDP     TOT  MLN_USD  2022  1.254459e+06
95      NZL       GDP     TOT  MLN_USD  2018  2.083120e+05
96      NZL       GDP     TOT  MLN_USD  2019  2.281651e+05
97      NZL       GDP     TOT  MLN_USD  2020  2.316998e+05
98      NZL       GDP     TOT  MLN_USD  2021  2.453640e+05
99      NZL       GDP     TOT  MLN_USD  2022  2.647876e+05
100     NOR       GDP     TOT  MLN_USD  2018  3.731825e+05
101     NOR       GDP     TOT  MLN_USD  2019  3.739055e+05
102     NOR       GDP     TOT  MLN_USD  2020  3.503661e+05
103     NOR       GDP     TOT  MLN_USD  2021  4.427618e+05
104     NOR       GDP     TOT  MLN_USD  2022  6.271850e+05
105     POL       GDP     TOT  MLN_USD  2018  1.216240e+06
106     POL       GDP     TOT  MLN_USD  2019  1.327882e+06
107     POL       GDP     TOT  MLN_USD  2020  1.338433e+06
108     POL       GDP     TOT  MLN_USD  2021  1.443515e+06
109     POL       GDP     TOT  MLN_USD  2022  1.625114e+06
110     PRT       GDP     TOT  MLN_USD  2018  3.591989e+05
111     PRT       GDP     TOT  MLN_USD  2019  3.836706e+05
112     PRT       GDP     TOT  MLN_USD  2020  3.599414e+05
113     PRT       GDP     TOT  MLN_USD  2021  3.806044e+05
114     PRT       GDP     TOT  MLN_USD  2022  4.357787e+05
115     SVK       GDP     TOT  MLN_USD  2018  1.708642e+05
116     SVK       GDP     TOT  MLN_USD  2019  1.824619e+05
117     SVK       GDP     TOT  MLN_USD  2020  1.797202e+05
118     SVK       GDP     TOT  MLN_USD  2021  1.879590e+05
119     SVK       GDP     TOT  MLN_USD  2022  2.034581e+05
120     ESP       GDP     TOT  MLN_USD  2018  1.905450e+06
121     ESP       GDP     TOT  MLN_USD  2019  2.031925e+06
122     ESP       GDP     TOT  MLN_USD  2020  1.800971e+06
123     ESP       GDP     TOT  MLN_USD  2021  1.952699e+06
124     ESP       GDP     TOT  MLN_USD  2022  2.213649e+06
125     SWE       GDP     TOT  MLN_USD  2018  5.445941e+05
126     SWE       GDP     TOT  MLN_USD  2019  5.797734e+05
127     SWE       GDP     TOT  MLN_USD  2020  5.812479e+05
128     SWE       GDP     TOT  MLN_USD  2021  6.290808e+05
129     SWE       GDP     TOT  MLN_USD  2022  6.839092e+05
130     CHE       GDP     TOT  MLN_USD  2018  6.018680e+05
131     CHE       GDP     TOT  MLN_USD  2019  6.231547e+05
132     CHE       GDP     TOT  MLN_USD  2020  6.134001e+05
133     CHE       GDP     TOT  MLN_USD  2021  6.718286e+05
134     CHE       GDP     TOT  MLN_USD  2022  7.428678e+05
135     TUR       GDP     TOT  MLN_USD  2018  2.302310e+06
136     TUR       GDP     TOT  MLN_USD  2019  2.313147e+06
137     TUR       GDP     TOT  MLN_USD  2020  2.332604e+06
138     TUR       GDP     TOT  MLN_USD  2021  2.581588e+06
139     TUR       GDP     TOT  MLN_USD  2022  3.180984e+06
140     GBR       GDP     TOT  MLN_USD  2018  3.129648e+06
141     GBR       GDP     TOT  MLN_USD  2019  3.287762e+06
142     GBR       GDP     TOT  MLN_USD  2020  3.069412e+06
143     GBR       GDP     TOT  MLN_USD  2021  3.375529e+06
144     GBR       GDP     TOT  MLN_USD  2022  3.678730e+06
145     USA       GDP     TOT  MLN_USD  2018  2.053306e+07
146     USA       GDP     TOT  MLN_USD  2019  2.138098e+07
147     USA       GDP     TOT  MLN_USD  2020  2.106047e+07
148     USA       GDP     TOT  MLN_USD  2021  2.331508e+07
149     USA       GDP     TOT  MLN_USD  2022  2.543970e+07
150     CHL       GDP     TOT  MLN_USD  2018  4.780939e+05
151     CHL       GDP     TOT  MLN_USD  2019  4.874145e+05
152     CHL       GDP     TOT  MLN_USD  2020  4.813737e+05
153     CHL       GDP     TOT  MLN_USD  2021  5.523798e+05
154     CHL       GDP     TOT  MLN_USD  2022  5.922054e+05
155     COL       GDP     TOT  MLN_USD  2018  7.471037e+05
156     COL       GDP     TOT  MLN_USD  2019  7.965900e+05
157     COL       GDP     TOT  MLN_USD  2020  7.692095e+05
158     COL       GDP     TOT  MLN_USD  2021  8.811909e+05
159     COL       GDP     TOT  MLN_USD  2022  1.051418e+06
160     EST       GDP     TOT  MLN_USD  2018  4.813337e+04
161     EST       GDP     TOT  MLN_USD  2019  5.175855e+04
162     EST       GDP     TOT  MLN_USD  2020  5.243878e+04
163     EST       GDP     TOT  MLN_USD  2021  5.786471e+04
164     EST       GDP     TOT  MLN_USD  2022  6.279708e+04
165     ISR       GDP     TOT  MLN_USD  2018  3.559103e+05
166     ISR       GDP     TOT  MLN_USD  2019  3.680485e+05
167     ISR       GDP     TOT  MLN_USD  2020  3.692462e+05
168     ISR       GDP     TOT  MLN_USD  2021  4.136510e+05
169     ISR       GDP     TOT  MLN_USD  2022  4.755312e+05
170     SVN       GDP     TOT  MLN_USD  2018  8.082348e+04
171     SVN       GDP     TOT  MLN_USD  2019  8.798655e+04
172     SVN       GDP     TOT  MLN_USD  2020  8.597404e+04
173     SVN       GDP     TOT  MLN_USD  2021  9.282665e+04
174     SVN       GDP     TOT  MLN_USD  2022  1.020143e+05
175    OECD       GDP     TOT  MLN_USD  2018  6.125256e+07
176    OECD       GDP     TOT  MLN_USD  2019  6.365248e+07
177    OECD       GDP     TOT  MLN_USD  2020  6.218445e+07
178    OECD       GDP     TOT  MLN_USD  2021  6.762283e+07
179    OECD       GDP     TOT  MLN_USD  2022  7.462769e+07
180     LVA       GDP     TOT  MLN_USD  2018  5.950549e+04
181     LVA       GDP     TOT  MLN_USD  2019  6.280072e+04
182     LVA       GDP     TOT  MLN_USD  2020  6.236782e+04
183     LVA       GDP     TOT  MLN_USD  2021  6.552304e+04
184     LVA       GDP     TOT  MLN_USD  2022  7.484688e+04
185     LTU       GDP     TOT  MLN_USD  2018  1.019104e+05
186     LTU       GDP     TOT  MLN_USD  2019  1.117447e+05
187     LTU       GDP     TOT  MLN_USD  2020  1.123875e+05
188     LTU       GDP     TOT  MLN_USD  2021  1.233768e+05
189     LTU       GDP     TOT  MLN_USD  2022  1.383559e+05
190     CRI       GDP     TOT  MLN_USD  2018  1.065833e+05
191     CRI       GDP     TOT  MLN_USD  2019  1.149523e+05
192     CRI       GDP     TOT  MLN_USD  2020  1.111390e+05
193     CRI       GDP     TOT  MLN_USD  2021  1.167036e+05
194     CRI       GDP     TOT  MLN_USD  2022  1.291200e+05>

In [51]:
newgdp_df.shape

(195, 6)

In [52]:
newcar2_regist.head(2)

  COUNTRY INDICATOR SUBJECT  MEASURE  YEAR  VALUE_PASSCAR
0     AUS   PASSCAR     TOT  IDX2015  2015     100.000000
1     AUS   PASSCAR     TOT  IDX2015  2016      94.293781

In [53]:
newcar2_regist.shape

(231, 6)

Given that the datasets 'infra_invest' and 'passenger_transport' include the identical observations for the 'COUNTRY' and 'YEAR' columns, a more precise merge utilising these two keys was performed. This method will align the data more properly and avoid missing values. Because the datasets 1 and 2 have comparable columns and observations, they were joined using the procedure `on how=left`. The merging technique `on how=outer` was tested with the key columns COUNTRY', 'YEAR', and 'SUBJECT', however the outputs had too many missing data.

In [54]:
# Merging the DataFrames on 'COUNTRY' and 'YEAR'
combined_df = pd.merge(newinfra_invest_df, newpassenger_transp, on=['COUNTRY', 'YEAR',], how='left')

# Display the first few rows of the combined DataFrame
combined_df.head(2)

,COUNTRY,INDICATOR_x,SUBJECT_x,MEASURE_x,YEAR,VALUE_INFRAINVEST,INDICATOR_y,SUBJECT_y,MEASURE_y,VALUE_PASSTRANSP
0,AUS,INFRAINVEST,RAIL,EUR,2018,4.628355e+09,PASSTRANSP,RAIL,MLN_PKM,17157.920674
1,AUS,INFRAINVEST,RAIL,EUR,2018,4.628355e+09,PASSTRANSP,ROAD,MLN_PKM,304707.073631

In [55]:
combined_df.shape

(363, 10)

In [56]:
combined_df.isnull().values.any()

False

In [73]:
# Rename columns and DataFrame
infrainvest_passtransp_df = combined_df .rename(columns={'INDICATOR_x': 'INDIC_INFRAINVEST', 'SUBJECT_x': 'SUBJECT_INFRA', 'MEASURE_x': 'VALUE_EUR',
                                                         'INDICATOR_y': 'INDIC_PASSTRANSP', 'SUBJECT_y': 'SUBJECT_PASSTRANSP','MEASURE_y':'MEASURE_PKM'})

# Remove the 'YEAR' column and store it
year_column = infrainvest_passtransp_df.pop('YEAR')

# Insert the 'YEAR' column back in the DataFrame after the 'COUNTRY' column
infrainvest_passtransp_df.insert(1, 'YEAR', year_column)

#Dysplay the Dataset
infrainvest_passtransp_df

,COUNTRY,YEAR,INDIC_INFRAINVEST,SUBJECT_INFRA,VALUE_EUR,VALUE_INFRAINVEST,INDIC_PASSTRANSP,SUBJECT_PASSTRANSP,MEASURE_PKM,VALUE_PASSTRANSP
0,AUS,2018,INFRAINVEST,RAIL,EUR,4.628355e+09,PASSTRANSP,RAIL,MLN_PKM,1.715792e+04
1,AUS,2018,INFRAINVEST,RAIL,EUR,4.628355e+09,PASSTRANSP,ROAD,MLN_PKM,3.047071e+05
2,AUS,2019,INFRAINVEST,RAIL,EUR,4.935198e+09,PASSTRANSP,RAIL,MLN_PKM,1.781417e+04
3,AUS,2019,INFRAINVEST,RAIL,EUR,4.935198e+09,PASSTRANSP,ROAD,MLN_PKM,3.035458e+05
4,AUS,2020,INFRAINVEST,RAIL,EUR,5.192725e+09,PASSTRANSP,RAIL,MLN_PKM,1.416645e+04
5,AUS,2020,INFRAINVEST,RAIL,EUR,5.192725e+09,PASSTRANSP,ROAD,MLN_PKM,2.775920e+05
6,AUS,2021,INFRAINVEST,RAIL,EUR,6.750072e+09,PASSTRANSP,RAIL,MLN_PKM,8.845193e+03
7,AUS,2021,INFRAINVEST,RAIL,EUR,6.750072e+09,PASSTRANSP,ROAD,MLN_PKM,2.753086e+05
8,AUS,2018,INFRAINVEST,ROAD,EUR,1.436391e+10,PASSTRANSP,RAIL,MLN_PKM,1.715792e+04
9,AUS,2018,INFRAINVEST,ROAD,EUR,1.436391e+10,PASSTRANSP,ROAD,MLN_PKM,3.047071e+05
10,AUS,2019,INFRAINVEST,ROAD,EUR,1.331767e+10,PASSTRANSP,RAIL,MLN_PKM,1.781417e+04
11,AUS,2019,INFRAINVEST,ROAD,EUR,1.331767e+10,PASSTRANSP,ROAD,MLN_PKM,3.035458e+05
12,AUS,2020,INFRAINVEST,ROAD,EUR,1.267147e+10,PASSTRANSP,RAIL,MLN_PKM,1.416645e+04
13,AUS,2020,INFRAINVEST,ROAD,EUR,1.267147e+10,PASSTRANSP,ROAD,MLN_PKM,2.775920e+05
14,AUS,2021,INFRAINVEST,ROAD,EUR,1.328682e+10,PASSTRANSP,RAIL,MLN_PKM,8.845193e+03
15,AUS,2021,INFRAINVEST,ROAD,EUR,1.328682e+10,PASSTRANSP,ROAD,MLN_PKM,2.753086e+05
16,AUT,2018,INFRAINVEST,RAIL,EUR,1.682000e+09,PASSTRANSP,RAIL,MLN_PKM,1.320470e+04
17,AUT,2019,INFRAINVEST,RAIL,EUR,1.737000e+09,PASSTRANSP,RAIL,MLN_PKM,1.335000e+04
18,AUT,2020,INFRAINVEST,RAIL,EUR,2.002000e+09,PASSTRANSP,RAIL,MLN_PKM,7.417005e+03
19,AUT,2021,INFRAINVEST,RAIL,EUR,2.249500e+09,PASSTRANSP,RAIL,MLN_PKM,8.433154e+03
20,AUT,2018,INFRAINVEST,ROAD,EUR,4.630000e+08,PASSTRANSP,RAIL,MLN_PKM,1.320470e+04
21,AUT,2019,INFRAINVEST,ROAD,EUR,5.620000e+08,PASSTRANSP,RAIL,MLN_PKM,1.335000e+04
22,AUT,2020,INFRAINVEST,ROAD,EUR,5.480000e+08,PASSTRANSP,RAIL,MLN_PKM,7.417005e+03
23,AUT,2021,INFRAINVEST,ROAD,EUR,4.800000e+08,PASSTRANSP,RAIL,MLN_PKM,8.433154e+03
24,BEL,2018,INFRAINVEST,RAIL,EUR,9.260000e+08,PASSTRANSP,RAIL,MLN_PKM,1.050000e+04
25,BEL,2019,INFRAINVEST,RAIL,EUR,8.990000e+08,PASSTRANSP,RAIL,MLN_PKM,1.084900e+04
26,BEL,2020,INFRAINVEST,RAIL,EUR,1.008252e+09,PASSTRANSP,RAIL,MLN_PKM,7.397000e+03
27,BEL,2021,INFRAINVEST,RAIL,EUR,1.137261e+09,PASSTRANSP,RAIL,MLN_PKM,6.970000e+03
28,BEL,2018,INFRAINVEST,ROAD,EUR,6.810000e+08,PASSTRANSP,RAIL,MLN_PKM,1.050000e+04
29,BEL,2019,INFRAINVEST,ROAD,EUR,7.350000e+08,PASSTRANSP,RAIL,MLN_PKM,1.084900e+04
30,BEL,2020,INFRAINVEST,ROAD,EUR,6.070000e+08,PASSTRANSP,RAIL,MLN_PKM,7.397000e+03
31,BEL,2021,INFRAINVEST,ROAD,EUR,1.311000e+09,PASSTRANSP,RAIL,MLN_PKM,6.970000e+03
32,CAN,2018,INFRAINVEST,RAIL,EUR,1.081558e+09,PASSTRANSP,RAIL,MLN_PKM,1.529936e+03
33,CAN,2019,INFRAINVEST,RAIL,EUR,1.366359e+09,PASSTRANSP,RAIL,MLN_PKM,1.730988e+03
34,CAN,2018,INFRAINVEST,ROAD,EUR,6.431185e+09,PASSTRANSP,RAIL,MLN_PKM,1.529936e+03
35,CAN,2019,INFRAINVEST,ROAD,EUR,7.543246e+09,PASSTRANSP,RAIL,MLN_PKM,1.730988e+03
36,CZE,2018,INFRAINVEST,RAIL,EUR,7.410570e+08,PASSTRANSP,RAIL,MLN_PKM,1.028602e+04
37,CZE,2018,INFRAINVEST,RAIL,EUR,7.410570e+08,PASSTRANSP,ROAD,MLN_PKM,8.892140e+04
38,CZE,2019,INFRAINVEST,RAIL,EUR,7.628419e+08,PASSTRANSP,RAIL,MLN_PKM,1.093062e+04
39,CZE,2019,INFRAINVEST,RAIL,EUR,7.628419e+08,PASSTRANSP,ROAD,MLN_PKM,9.172600e+04
40,CZE,2020,INFRAINVEST,RAIL,EUR,1.123320e+09,PASSTRANSP,RAIL,MLN_PKM,6.665141e+03
41,CZE,2020,INFRAINVEST,RAIL,EUR,1.123320e+09,PASSTRANSP,ROAD,MLN_PKM,7.438000e+04
42,CZE,2021,INFRAINVEST,RAIL,EUR,1.448914e+09,PASSTRANSP,RAIL,MLN_PKM,6.820176e+03
43,CZE,2021,INFRAINVEST,RAIL,EUR,1.448914e+09,PASSTRANSP,ROAD,MLN_PKM,9.333513e+04
44,CZE,2018,INFRAINVEST,ROAD,EUR,1.044764e+09,PASSTRANSP,RAIL,MLN_PKM,1.028602e+04
45,CZE,2018,INFRAINVEST,ROAD,EUR,1.044764e+09,PASSTRANSP,ROAD,MLN_PKM,8.892140e+04
46,CZE,2019,INFRAINVEST,ROAD,EUR,1.383065e+09,PASSTRANSP,RAIL,MLN_PKM,1.093062e+04
47,CZE,2019,INFRAINVEST,ROAD,EUR,1.383065e+09,PASSTRANSP,ROAD,MLN_PKM,9.172600e+04
48,CZE,2020,INFRAINVEST,ROAD,EUR,1.640906e+09,PASSTRANSP,RAIL,MLN_PKM,6.665141e+03
49,CZE,2020,INFRAINVEST,ROAD,EUR,1.640906e+09,PASSTRANSP,ROAD,MLN_PKM,7.438000e+04
50,CZE,2021,INFRAINVEST,ROAD,EUR,1.817147e+09,PASSTRANSP,RAIL,MLN_PKM,6.820176e+03
51,CZE,2021,INFRAINVEST,ROAD,EUR,1.817147e+09,PASSTRANSP,ROAD,MLN_PKM,9.333513e+04
52,DNK,2018,INFRAINVEST,RAIL,EUR,1.351366e+09,PASSTRANSP,RAIL,MLN_PKM,6.560000e+03
53,DNK,2018,INFRAINVEST,ROAD,EUR,1.083964e+09,PASSTRANSP,RAIL,MLN_PKM,6.560000e+03
54,FIN,2018,INFRAINVEST,RAIL,EUR,4.910000e+08,PASSTRANSP,RAIL,MLN_PKM,4.534000e+03
55,FIN,2018,INFRAINVEST,RAIL,EUR,4.910000e+08,PASSTRANSP,ROAD,MLN_PKM,7.480000e+04
56,FIN,2019,INFRAINVEST,RAIL,EUR,4.620000e+08,PASSTRANSP,RAIL,MLN_PKM,4.924000e+03
57,FIN,2019,INFRAINVEST,RAIL,EUR,4.620000e+08,PASSTRANSP,ROAD,MLN_PKM,7.470000e+04
58,FIN,2020,INFRAINVEST,RAIL,EUR,6.840000e+08,PASSTRANSP,RAIL,MLN_PKM,2.820000e+03
59,FIN,2020,INFRAINVEST,RAIL,EUR,6.840000e+08,PASSTRANSP,ROAD,MLN_PKM,7.090000e+04
60,FIN,2021,INFRAINVEST,RAIL,EUR,6.060000e+08,PASSTRANSP,RAIL,MLN_PKM,2.903000e+03
61,FIN,2021,INFRAINVEST,RAIL,EUR,6.060000e+08,PASSTRANSP,ROAD,MLN_PKM,6.960000e+04
62,FIN,2018,INFRAINVEST,ROAD,EUR,1.526000e+09,PASSTRANSP,RAIL,MLN_PKM,4.534000e+03
63,FIN,2018,INFRAINVEST,ROAD,EUR,1.526000e+09,PASSTRANSP,ROAD,MLN_PKM,7.480000e+04
64,FIN,2019,INFRAINVEST,ROAD,EUR,1.522000e+09,PASSTRANSP,RAIL,MLN_PKM,4.924000e+03
65,FIN,2019,INFRAINVEST,ROAD,EUR,1.522000e+09,PASSTRANSP,ROAD,MLN_PKM,7.470000e+04
66,FIN,2020,INFRAINVEST,ROAD,EUR,1.444000e+09,PASSTRANSP,RAIL,MLN_PKM,2.820000e+03
67,FIN,2020,INFRAINVEST,ROAD,EUR,1.444000e+09,PASSTRANSP,ROAD,MLN_PKM,7.090000e+04
68,FIN,2021,INFRAINVEST,ROAD,EUR,1.375000e+09,PASSTRANSP,RAIL,MLN_PKM,2.903000e+03
69,FIN,2021,INFRAINVEST,ROAD,EUR,1.375000e+09,PASSTRANSP,ROAD,MLN_PKM,6.960000e+04
70,FRA,2018,INFRAINVEST,RAIL,EUR,1.028488e+10,PASSTRANSP,RAIL,MLN_PKM,1.078730e+05
71,FRA,2018,INFRAINVEST,RAIL,EUR,1.028488e+10,PASSTRANSP,ROAD,MLN_PKM,8.986100e+05
72,FRA,2019,INFRAINVEST,RAIL,EUR,1.152838e+10,PASSTRANSP,RAIL,MLN_PKM,1.123090e+05
73,FRA,2019,INFRAINVEST,RAIL,EUR,1.152838e+10,PASSTRANSP,ROAD,MLN_PKM,9.063420e+05
74,FRA,2020,INFRAINVEST,RAIL,EUR,1.078938e+10,PASSTRANSP,RAIL,MLN_PKM,6.481600e+04
75,FRA,2020,INFRAINVEST,RAIL,EUR,1.078938e+10,PASSTRANSP,ROAD,MLN_PKM,7.165750e+05
76,FRA,2021,INFRAINVEST,RAIL,EUR,1.155764e+10,PASSTRANSP,RAIL,MLN_PKM,8.641900e+04
77,FRA,2021,INFRAINVEST,RAIL,EUR,1.155764e+10,PASSTRANSP,ROAD,MLN_PKM,7.775090e+05
78,FRA,2018,INFRAINVEST,ROAD,EUR,9.883630e+09,PASSTRANSP,RAIL,MLN_PKM,1.078730e+05
79,FRA,2018,INFRAINVEST,ROAD,EUR,9.883630e+09,PASSTRANSP,ROAD,MLN_PKM,8.986100e+05
80,FRA,2019,INFRAINVEST,ROAD,EUR,1.041300e+10,PASSTRANSP,RAIL,MLN_PKM,1.123090e+05
81,FRA,2019,INFRAINVEST,ROAD,EUR,1.041300e+10,PASSTRANSP,ROAD,MLN_PKM,9.063420e+05
82,FRA,2020,INFRAINVEST,ROAD,EUR,9.630572e+09,PASSTRANSP,RAIL,MLN_PKM,6.481600e+04
83,FRA,2020,INFRAINVEST,ROAD,EUR,9.630572e+09,PASSTRANSP,ROAD,MLN_PKM,7.165750e+05
84,FRA,2021,INFRAINVEST,ROAD,EUR,1.015339e+10,PASSTRANSP,RAIL,MLN_PKM,8.641900e+04
85,FRA,2021,INFRAINVEST,ROAD,EUR,1.015339e+10,PASSTRANSP,ROAD,MLN_PKM,7.775090e+05
86,DEU,2018,INFRAINVEST,RAIL,EUR,7.590000e+09,PASSTRANSP,RAIL,MLN_PKM,9.817000e+04
87,DEU,2018,INFRAINVEST,RAIL,EUR,7.590000e+09,PASSTRANSP,ROAD,MLN_PKM,9.787020e+05
88,DEU,2019,INFRAINVEST,RAIL,EUR,8.577000e+09,PASSTRANSP,RAIL,MLN_PKM,1.020260e+05
89,DEU,2019,INFRAINVEST,RAIL,EUR,8.577000e+09,PASSTRANSP,ROAD,MLN_PKM,9.814520e+05
90,DEU,2020,INFRAINVEST,RAIL,EUR,9.615000e+09,PASSTRANSP,RAIL,MLN_PKM,5.882200e+04
91,DEU,2020,INFRAINVEST,RAIL,EUR,9.615000e+09,PASSTRANSP,ROAD,MLN_PKM,8.311410e+05
92,DEU,2021,INFRAINVEST,RAIL,EUR,1.007800e+10,PASSTRANSP,RAIL,MLN_PKM,5.753300e+04
93,DEU,2021,INFRAINVEST,RAIL,EUR,1.007800e+10,PASSTRANSP,ROAD,MLN_PKM,8.366250e+05
94,DEU,2018,INFRAINVEST,ROAD,EUR,1.581000e+10,PASSTRANSP,RAIL,MLN_PKM,9.817000e+04
95,DEU,2018,INFRAINVEST,ROAD,EUR,1.581000e+10,PASSTRANSP,ROAD,MLN_PKM,9.787020e+05
96,DEU,2019,INFRAINVEST,ROAD,EUR,1.675000e+10,PASSTRANSP,RAIL,MLN_PKM,1.020260e+05
97,DEU,2019,INFRAINVEST,ROAD,EUR,1.675000e+10,PASSTRANSP,ROAD,MLN_PKM,9.814520e+05
98,DEU,2020,INFRAINVEST,ROAD,EUR,1.709000e+10,PASSTRANSP,RAIL,MLN_PKM,5.882200e+04
99,DEU,2020,INFRAINVEST,ROAD,EUR,1.709000e+10,PASSTRANSP,ROAD,MLN_PKM,8.311410e+05
100,DEU,2021,INFRAINVEST,ROAD,EUR,1.645000e+10,PASSTRANSP,RAIL,MLN_PKM,5.753300e+04
101,DEU,2021,INFRAINVEST,ROAD,EUR,1.645000e+10,PASSTRANSP,ROAD,MLN_PKM,8.366250e+05
102,GRC,2018,INFRAINVEST,RAIL,EUR,1.509672e+08,PASSTRANSP,RAIL,MLN_PKM,1.104000e+03
103,GRC,2019,INFRAINVEST,RAIL,EUR,9.785557e+07,PASSTRANSP,RAIL,MLN_PKM,1.252000e+03
104,GRC,2020,INFRAINVEST,RAIL,EUR,5.089510e+07,PASSTRANSP,RAIL,MLN_PKM,6.400000e+02
105,GRC,2021,INFRAINVEST,RAIL,EUR,4.938498e+07,PASSTRANSP,RAIL,MLN_PKM,6.530000e+02
106,GRC,2018,INFRAINVEST,ROAD,EUR,2.158003e+09,PASSTRANSP,RAIL,MLN_PKM,1.104000e+03
107,GRC,2019,INFRAINVEST,ROAD,EUR,7.408717e+08,PASSTRANSP,RAIL,MLN_PKM,1.252000e+03
108,GRC,2020,INFRAINVEST,ROAD,EUR,7.809844e+08,PASSTRANSP,RAIL,MLN_PKM,6.400000e+02
109,GRC,2021,INFRAINVEST,ROAD,EUR,7.307170e+08,PASSTRANSP,RAIL,MLN_PKM,6.530000e+02
110,HUN,2018,INFRAINVEST,RAIL,EUR,8.031293e+08,PASSTRANSP,RAIL,MLN_PKM,7.769560e+03
111,HUN,2018,INFRAINVEST,RAIL,EUR,8.031293e+08,PASSTRANSP,ROAD,MLN_PKM,8.260692e+04
112,HUN,2019,INFRAINVEST,RAIL,EUR,8.798429e+08,PASSTRANSP,RAIL,MLN_PKM,7.751606e+03
113,HUN,2019,INFRAINVEST,RAIL,EUR,8.798429e+08,PASSTRANSP,ROAD,MLN_PKM,8.575624e+04
114,HUN,2020,INFRAINVEST,RAIL,EUR,7.176219e+08,PASSTRANSP,RAIL,MLN_PKM,4.854225e+03
115,HUN,2020,INFRAINVEST,RAIL,EUR,7.176219e+08,PASSTRANSP,ROAD,MLN_PKM,7.715023e+04
116,HUN,2021,INFRAINVEST,RAIL,EUR,6.455158e+08,PASSTRANSP,RAIL,MLN_PKM,5.435389e+03
117,HUN,2021,INFRAINVEST,RAIL,EUR,6.455158e+08,PASSTRANSP,ROAD,MLN_PKM,8.044748e+04
118,HUN,2018,INFRAINVEST,ROAD,EUR,1.780314e+09,PASSTRANSP,RAIL,MLN_PKM,7.769560e+03
119,HUN,2018,INFRAINVEST,ROAD,EUR,1.780314e+09,PASSTRANSP,ROAD,MLN_PKM,8.260692e+04
120,HUN,2019,INFRAINVEST,ROAD,EUR,2.288587e+09,PASSTRANSP,RAIL,MLN_PKM,7.751606e+03
121,HUN,2019,INFRAINVEST,ROAD,EUR,2.288587e+09,PASSTRANSP,ROAD,MLN_PKM,8.575624e+04
122,HUN,2020,INFRAINVEST,ROAD,EUR,1.820222e+09,PASSTRANSP,RAIL,MLN_PKM,4.854225e+03
123,HUN,2020,INFRAINVEST,ROAD,EUR,1.820222e+09,PASSTRANSP,ROAD,MLN_PKM,7.715023e+04
124,HUN,2021,INFRAINVEST,ROAD,EUR,1.894279e+09,PASSTRANSP,RAIL,MLN_PKM,5.435389e+03
125,HUN,2021,INFRAINVEST,ROAD,EUR,1.894279e+09,PASSTRANSP,ROAD,MLN_PKM,8.044748e+04
126,ISL,2018,INFRAINVEST,ROAD,EUR,9.986750e+07,PASSTRANSP,ROAD,MLN_PKM,8.235000e+03
127,ISL,2019,INFRAINVEST,ROAD,EUR,9.169577e+07,PASSTRANSP,ROAD,MLN_PKM,8.167000e+03
128,ISL,2020,INFRAINVEST,ROAD,EUR,1.072526e+08,PASSTRANSP,ROAD,MLN_PKM,6.316000e+03
129,ISL,2021,INFRAINVEST,ROAD,EUR,1.043145e+08,PASSTRANSP,ROAD,MLN_PKM,7.557000e+03
130,IRL,2018,INFRAINVEST,RAIL,EUR,4.361057e+07,PASSTRANSP,RAIL,MLN_PKM,2.281000e+03
131,IRL,2019,INFRAINVEST,RAIL,EUR,7.188900e+07,PASSTRANSP,RAIL,MLN_PKM,2.399000e+03
132,IRL,2020,INFRAINVEST,RAIL,EUR,1.010000e+08,PASSTRANSP,RAIL,MLN_PKM,8.340000e+02
133,IRL,2018,INFRAINVEST,ROAD,EUR,6.930000e+08,PASSTRANSP,RAIL,MLN_PKM,2.281000e+03
134,IRL,2019,INFRAINVEST,ROAD,EUR,8.370000e+08,PASSTRANSP,RAIL,MLN_PKM,2.399000e+03
135,ITA,2018,INFRAINVEST,RAIL,EUR,2.855000e+09,PASSTRANSP,RAIL,MLN_PKM,5.549300e+04
136,ITA,2018,INFRAINVEST,RAIL,EUR,2.855000e+09,PASSTRANSP,ROAD,MLN_PKM,8.254940e+05
137,ITA,2019,INFRAINVEST,RAIL,EUR,4.246000e+09,PASSTRANSP,RAIL,MLN_PKM,5.658600e+04
138,ITA,2019,INFRAINVEST,RAIL,EUR,4.246000e+09,PASSTRANSP,ROAD,MLN_PKM,8.367220e+05
139,ITA,2020,INFRAINVEST,RAIL,EUR,9.768000e+09,PASSTRANSP,RAIL,MLN_PKM,2.226900e+04
140,ITA,2020,INFRAINVEST,RAIL,EUR,9.768000e+09,PASSTRANSP,ROAD,MLN_PKM,5.194390e+05
141,ITA,2018,INFRAINVEST,ROAD,EUR,6.555000e+09,PASSTRANSP,RAIL,MLN_PKM,5.549300e+04
142,ITA,2018,INFRAINVEST,ROAD,EUR,6.555000e+09,PASSTRANSP,ROAD,MLN_PKM,8.254940e+05
143,ITA,2019,INFRAINVEST,ROAD,EUR,4.310000e+09,PASSTRANSP,RAIL,MLN_PKM,5.658600e+04
144,ITA,2019,INFRAINVEST,ROAD,EUR,4.310000e+09,PASSTRANSP,ROAD,MLN_PKM,8.367220e+05
145,ITA,2020,INFRAINVEST,ROAD,EUR,4.393000e+09,PASSTRANSP,RAIL,MLN_PKM,2.226900e+04
146,ITA,2020,INFRAINVEST,ROAD,EUR,4.393000e+09,PASSTRANSP,ROAD,MLN_PKM,5.194390e+05
147,JPN,2018,INFRAINVEST,RAIL,EUR,1.512362e+10,PASSTRANSP,RAIL,MLN_PKM,4.416140e+05
148,JPN,2018,INFRAINVEST,RAIL,EUR,1.512362e+10,PASSTRANSP,ROAD,MLN_PKM,9.126330e+05
149,JPN,2019,INFRAINVEST,RAIL,EUR,1.755989e+10,PASSTRANSP,RAIL,MLN_PKM,4.350630e+05
150,JPN,2019,INFRAINVEST,RAIL,EUR,1.755989e+10,PASSTRANSP,ROAD,MLN_PKM,9.053430e+05
151,JPN,2020,INFRAINVEST,RAIL,EUR,1.701974e+10,PASSTRANSP,RAIL,MLN_PKM,2.632110e+05
152,JPN,2020,INFRAINVEST,RAIL,EUR,1.701974e+10,PASSTRANSP,ROAD,MLN_PKM,7.694400e+05
153,JPN,2018,INFRAINVEST,ROAD,EUR,3.002726e+10,PASSTRANSP,RAIL,MLN_PKM,4.416140e+05
154,JPN,2018,INFRAINVEST,ROAD,EUR,3.002726e+10,PASSTRANSP,ROAD,MLN_PKM,9.126330e+05
155,JPN,2019,INFRAINVEST,ROAD,EUR,3.282990e+10,PASSTRANSP,RAIL,MLN_PKM,4.350630e+05
156,JPN,2019,INFRAINVEST,ROAD,EUR,3.282990e+10,PASSTRANSP,ROAD,MLN_PKM,9.053430e+05
157,KOR,2018,INFRAINVEST,RAIL,EUR,5.366737e+09,PASSTRANSP,RAIL,MLN_PKM,9.219300e+04
158,KOR,2018,INFRAINVEST,RAIL,EUR,5.366737e+09,PASSTRANSP,ROAD,MLN_PKM,3.872680e+05
159,KOR,2019,INFRAINVEST,RAIL,EUR,6.278663e+09,PASSTRANSP,RAIL,MLN_PKM,1.003810e+05
160,KOR,2019,INFRAINVEST,RAIL,EUR,6.278663e+09,PASSTRANSP,ROAD,MLN_PKM,3.879570e+05
161,KOR,2018,INFRAINVEST,ROAD,EUR,1.212386e+10,PASSTRANSP,RAIL,MLN_PKM,9.219300e+04
162,KOR,2018,INFRAINVEST,ROAD,EUR,1.212386e+10,PASSTRANSP,ROAD,MLN_PKM,3.872680e+05
163,KOR,2019,INFRAINVEST,ROAD,EUR,1.320545e+10,PASSTRANSP,RAIL,MLN_PKM,1.003810e+05
164,KOR,2019,INFRAINVEST,ROAD,EUR,1.320545e+10,PASSTRANSP,ROAD,MLN_PKM,3.879570e+05
165,LUX,2018,INFRAINVEST,RAIL,EUR,2.639179e+08,PASSTRANSP,RAIL,MLN_PKM,4.420000e+02
166,LUX,2019,INFRAINVEST,RAIL,EUR,2.354496e+08,PASSTRANSP,RAIL,MLN_PKM,4.630000e+02
167,LUX,2020,INFRAINVEST,RAIL,EUR,2.657789e+08,PASSTRANSP,RAIL,MLN_PKM,2.690000e+02
168,LUX,2018,INFRAINVEST,ROAD,EUR,1.885960e+08,PASSTRANSP,RAIL,MLN_PKM,4.420000e+02
169,LUX,2019,INFRAINVEST,ROAD,EUR,2.600169e+08,PASSTRANSP,RAIL,MLN_PKM,4.630000e+02
170,LUX,2020,INFRAINVEST,ROAD,EUR,2.462255e+08,PASSTRANSP,RAIL,MLN_PKM,2.690000e+02
171,MEX,2018,INFRAINVEST,RAIL,EUR,1.455788e+09,PASSTRANSP,RAIL,MLN_PKM,1.591000e+03
172,MEX,2019,INFRAINVEST,RAIL,EUR,8.007873e+08,PASSTRANSP,RAIL,MLN_PKM,1.571000e+03
173,MEX,2020,INFRAINVEST,RAIL,EUR,3.980499e+08,PASSTRANSP,RAIL,MLN_PKM,5.230000e+02
174,MEX,2021,INFRAINVEST,RAIL,EUR,4.841226e+08,PASSTRANSP,RAIL,MLN_PKM,4.660000e+02
175,MEX,2018,INFRAINVEST,ROAD,EUR,2.304810e+09,PASSTRANSP,RAIL,MLN_PKM,1.591000e+03
176,MEX,2019,INFRAINVEST,ROAD,EUR,2.277117e+09,PASSTRANSP,RAIL,MLN_PKM,1.571000e+03
177,MEX,2020,INFRAINVEST,ROAD,EUR,1.532724e+09,PASSTRANSP,RAIL,MLN_PKM,5.230000e+02
178,MEX,2021,INFRAINVEST,ROAD,EUR,1.630623e+09,PASSTRANSP,RAIL,MLN_PKM,4.660000e+02
179,NZL,2018,INFRAINVEST,ROAD,EUR,1.057956e+09,PASSTRANSP,RAIL,MLN_PKM,7.432700e+02
180,NZL,2018,INFRAINVEST,ROAD,EUR,1.057956e+09,PASSTRANSP,ROAD,MLN_PKM,5.004346e+04
181,NZL,2019,INFRAINVEST,ROAD,EUR,1.041149e+09,PASSTRANSP,RAIL,MLN_PKM,7.765600e+02
182,NZL,2019,INFRAINVEST,ROAD,EUR,1.041149e+09,PASSTRANSP,ROAD,MLN_PKM,5.111894e+04
183,NZL,2020,INFRAINVEST,ROAD,EUR,1.376584e+09,PASSTRANSP,RAIL,MLN_PKM,8.020346e+02
184,NZL,2020,INFRAINVEST,ROAD,EUR,1.376584e+09,PASSTRANSP,ROAD,MLN_PKM,5.463001e+04
185,NZL,2021,INFRAINVEST,ROAD,EUR,1.012535e+09,PASSTRANSP,RAIL,MLN_PKM,7.380000e+02
186,NZL,2021,INFRAINVEST,ROAD,EUR,1.012535e+09,PASSTRANSP,ROAD,MLN_PKM,5.365800e+04
187,NOR,2018,INFRAINVEST,RAIL,EUR,1.316689e+09,PASSTRANSP,RAIL,MLN_PKM,3.684000e+03
188,NOR,2018,INFRAINVEST,RAIL,EUR,1.316689e+09,PASSTRANSP,ROAD,MLN_PKM,6.207800e+04
189,NOR,2019,INFRAINVEST,RAIL,EUR,1.537001e+09,PASSTRANSP,RAIL,MLN_PKM,3.676000e+03
190,NOR,2019,INFRAINVEST,RAIL,EUR,1.537001e+09,PASSTRANSP,ROAD,MLN_PKM,6.267100e+04
191,NOR,2020,INFRAINVEST,RAIL,EUR,1.476857e+09,PASSTRANSP,RAIL,MLN_PKM,1.798000e+03
192,NOR,2020,INFRAINVEST,RAIL,EUR,1.476857e+09,PASSTRANSP,ROAD,MLN_PKM,5.712600e+04
193,NOR,2018,INFRAINVEST,ROAD,EUR,4.060996e+09,PASSTRANSP,RAIL,MLN_PKM,3.684000e+03
194,NOR,2018,INFRAINVEST,ROAD,EUR,4.060996e+09,PASSTRANSP,ROAD,MLN_PKM,6.207800e+04
195,NOR,2019,INFRAINVEST,ROAD,EUR,4.051595e+09,PASSTRANSP,RAIL,MLN_PKM,3.676000e+03
196,NOR,2019,INFRAINVEST,ROAD,EUR,4.051595e+09,PASSTRANSP,ROAD,MLN_PKM,6.267100e+04
197,NOR,2020,INFRAINVEST,ROAD,EUR,3.272509e+09,PASSTRANSP,RAIL,MLN_PKM,1.798000e+03
198,NOR,2020,INFRAINVEST,ROAD,EUR,3.272509e+09,PASSTRANSP,ROAD,MLN_PKM,5.712600e+04
199,POL,2018,INFRAINVEST,RAIL,EUR,4.619068e+08,PASSTRANSP,RAIL,MLN_PKM,2.104300e+04
200,POL,2018,INFRAINVEST,RAIL,EUR,4.619068e+08,PASSTRANSP,ROAD,MLN_PKM,2.621560e+05
201,POL,2019,INFRAINVEST,RAIL,EUR,6.547993e+08,PASSTRANSP,RAIL,MLN_PKM,2.205600e+04
202,POL,2019,INFRAINVEST,RAIL,EUR,6.547993e+08,PASSTRANSP,ROAD,MLN_PKM,2.684910e+05
203,POL,2020,INFRAINVEST,RAIL,EUR,6.256752e+08,PASSTRANSP,RAIL,MLN_PKM,1.255700e+04
204,POL,2020,INFRAINVEST,RAIL,EUR,6.256752e+08,PASSTRANSP,ROAD,MLN_PKM,2.322340e+05
205,POL,2021,INFRAINVEST,RAIL,EUR,6.838300e+08,PASSTRANSP,RAIL,MLN_PKM,1.591700e+04
206,POL,2021,INFRAINVEST,RAIL,EUR,6.838300e+08,PASSTRANSP,ROAD,MLN_PKM,2.528070e+05
207,POL,2018,INFRAINVEST,ROAD,EUR,2.668638e+09,PASSTRANSP,RAIL,MLN_PKM,2.104300e+04
208,POL,2018,INFRAINVEST,ROAD,EUR,2.668638e+09,PASSTRANSP,ROAD,MLN_PKM,2.621560e+05
209,POL,2019,INFRAINVEST,ROAD,EUR,2.415358e+09,PASSTRANSP,RAIL,MLN_PKM,2.205600e+04
210,POL,2019,INFRAINVEST,ROAD,EUR,2.415358e+09,PASSTRANSP,ROAD,MLN_PKM,2.684910e+05
211,POL,2020,INFRAINVEST,ROAD,EUR,3.207598e+09,PASSTRANSP,RAIL,MLN_PKM,1.255700e+04
212,POL,2020,INFRAINVEST,ROAD,EUR,3.207598e+09,PASSTRANSP,ROAD,MLN_PKM,2.322340e+05
213,POL,2021,INFRAINVEST,ROAD,EUR,3.169807e+09,PASSTRANSP,RAIL,MLN_PKM,1.591700e+04
214,POL,2021,INFRAINVEST,ROAD,EUR,3.169807e+09,PASSTRANSP,ROAD,MLN_PKM,2.528070e+05
215,PRT,2018,INFRAINVEST,RAIL,EUR,1.320000e+08,PASSTRANSP,RAIL,MLN_PKM,4.487000e+03
216,PRT,2019,INFRAINVEST,RAIL,EUR,2.160000e+08,PASSTRANSP,RAIL,MLN_PKM,4.964014e+03
217,PRT,2020,INFRAINVEST,RAIL,EUR,2.200000e+08,PASSTRANSP,RAIL,MLN_PKM,2.552000e+03
218,PRT,2021,INFRAINVEST,RAIL,EUR,3.070000e+08,PASSTRANSP,RAIL,MLN_PKM,2.912000e+03
219,SVK,2018,INFRAINVEST,RAIL,EUR,2.794000e+08,PASSTRANSP,RAIL,MLN_PKM,3.915000e+03
220,SVK,2018,INFRAINVEST,RAIL,EUR,2.794000e+08,PASSTRANSP,ROAD,MLN_PKM,3.469900e+04
221,SVK,2020,INFRAINVEST,RAIL,EUR,1.768000e+08,PASSTRANSP,RAIL,MLN_PKM,2.180000e+03
222,SVK,2021,INFRAINVEST,RAIL,EUR,2.200000e+08,PASSTRANSP,RAIL,MLN_PKM,2.052000e+03
223,SVK,2018,INFRAINVEST,ROAD,EUR,7.688400e+08,PASSTRANSP,RAIL,MLN_PKM,3.915000e+03
224,SVK,2018,INFRAINVEST,ROAD,EUR,7.688400e+08,PASSTRANSP,ROAD,MLN_PKM,3.469900e+04
225,SVK,2020,INFRAINVEST,ROAD,EUR,7.522000e+08,PASSTRANSP,RAIL,MLN_PKM,2.180000e+03
226,SVK,2021,INFRAINVEST,ROAD,EUR,1.113000e+09,PASSTRANSP,RAIL,MLN_PKM,2.052000e+03
227,ESP,2018,INFRAINVEST,RAIL,EUR,2.168000e+09,PASSTRANSP,RAIL,MLN_PKM,2.843400e+04
228,ESP,2018,INFRAINVEST,RAIL,EUR,2.168000e+09,PASSTRANSP,ROAD,MLN_PKM,3.727440e+05
229,ESP,2019,INFRAINVEST,RAIL,EUR,2.218000e+09,PASSTRANSP,RAIL,MLN_PKM,2.883500e+04
230,ESP,2019,INFRAINVEST,RAIL,EUR,2.218000e+09,PASSTRANSP,ROAD,MLN_PKM,3.752550e+05
231,ESP,2020,INFRAINVEST,RAIL,EUR,2.380557e+09,PASSTRANSP,RAIL,MLN_PKM,1.198157e+04
232,ESP,2020,INFRAINVEST,RAIL,EUR,2.380557e+09,PASSTRANSP,ROAD,MLN_PKM,2.844670e+05
233,ESP,2021,INFRAINVEST,RAIL,EUR,2.519000e+09,PASSTRANSP,RAIL,MLN_PKM,1.747716e+04
234,ESP,2021,INFRAINVEST,RAIL,EUR,2.519000e+09,PASSTRANSP,ROAD,MLN_PKM,3.484020e+05
235,ESP,2018,INFRAINVEST,ROAD,EUR,3.518000e+09,PASSTRANSP,RAIL,MLN_PKM,2.843400e+04
236,ESP,2018,INFRAINVEST,ROAD,EUR,3.518000e+09,PASSTRANSP,ROAD,MLN_PKM,3.727440e+05

In [69]:
infrainvest_passtransp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 363 entries, 0 to 362
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COUNTRY             363 non-null    object
 1   YEAR                363 non-null    int64
 2   INDIC_INFRAINVEST   363 non-null    object
 3   SUBJECT_INFRA       363 non-null    object
 4   VALUE_EUR           363 non-null    object
 5   VALUE_INFRAINVEST   363 non-null    float64
 6   INDIC_PASSTRANSP    363 non-null    object
 7   SUBJECT_PASSTRANSP  363 non-null    object
 8   MEASURE_PKM         363 non-null    object
 9   VALUE_PASSTRANSP    363 non-null    float64
dtypes: float64(2), int64(1), object(7)
memory usage: 28.5+ KB

In [70]:
infrainvest_passtransp_df.nunique()

COUNTRY                35
YEAR                    4
INDIC_INFRAINVEST       1
SUBJECT_INFRA           2
VALUE_EUR               1
VALUE_INFRAINVEST     229
INDIC_PASSTRANSP        1
SUBJECT_PASSTRANSP      2
MEASURE_PKM             1
VALUE_PASSTRANSP      192
dtype: int64

In [71]:
infrainvest_passtransp_df.describe()

              YEAR  VALUE_INFRAINVEST  VALUE_PASSTRANSP
count   363.000000       3.630000e+02      3.630000e+02
mean   2019.344353       6.072274e+09      2.683691e+05
std       1.099920       1.395871e+10      9.382580e+05
min    2018.000000       2.090000e+07      2.600000e+02
25%    2018.000000       6.838300e+08      3.627950e+03
50%    2019.000000       2.002000e+09      2.061300e+04
75%    2020.000000       6.278663e+09      1.043312e+05
max    2021.000000       9.619507e+10      6.674065e+06

The use of concatenation as a data combining method is consistent with the goal of maintaining data completeness, transparency, and flexibility throughout the research process. It ensures that all data points, including those that do not have matches across all databases, are considered, allowing for a thorough study and interpretation of the combined data.

# Concatenate all the datasets
combined_df = pd.concat([newinfra_invest_df, newpassenger_transport, newgdp_df, newcar2_regist])

# Check the final combined data
combined_df.tail()

Create a Dictionary: First, create a dictionary that contains the mapping of country codes to country names. 

Automate the Mapping: Use this dictionary to replace the country codes in your dataset with their corresponding names.

# Dictionary for country code to name mapping
country_mapping = {
    'AUS': 'Australia', 'AUT': 'Austria', 'BEL': 'Belgium', 'CAN': 'Canada', 
    'CZE': 'Czech Republic', 'DNK': 'Denmark', 'FIN': 'Finland', 'FRA': 'France', 
    'DEU': 'Germany', 'GRC': 'Greece', 'HUN': 'Hungary', 'ISL': 'Iceland',
    'IRL': 'Ireland', 'ITA': 'Italy', 'JPN': 'Japan', 'KOR': 'South Korea', 
    'LUX': 'Luxembourg', 'MEX': 'Mexico', 'NZL': 'New Zealand', 'NOR': 'Norway', 
    'POL': 'Poland', 'PRT': 'Portugal', 'SVK': 'Slovakia', 'ESP': 'Spain',
    'SWE': 'Sweden', 'CHE': 'Switzerland', 'TUR': 'Turkey', 'GBR': 'United Kingdom', 
    'USA': 'United States', 'EST': 'Estonia', 'LVA': 'Latvia', 'LTU': 'Lithuania', 
    'SVN': 'Slovenia', 'ISR': 'Israel', 'CHL': 'Chile'
}

# Replace the country codes with names in the DataFrame
combined_df['LOCATION'] = combined_df['LOCATION'].map(country_mapping)

# Display the updated DataFrame
combined_df.head()