### MSC_DA_CA2

### Compare: Ireland (IRL)  with New Zealand (NZL), Finland (FIN) or Norway (NOR), Denmark (DNK), Portugal (PRT). 

Ireland's transport infrastructure can be compared to those of other countries in a variety of ways. Here are a few nations that may provide useful comparisons with Ireland in terms of economic growth, size, geography, and urban-rural dynamics:

Consider aspects such as the extent and quality of road and rail networks, investment in public transport, policies towards sustainable transportation, and the difficulty of providing connectivity in both urban and rural areas when comparing Ireland's transport infrastructure to that of these countries. While these countries share certain qualities with Ireland, they also have distinct characteristics due to their varied geographical, economic, and historical circumstances.

#### Dataset 1 : Infrastructure investment Rail and Road / Euro, 2021 

Source: Transport infrastructure investment and maintenance

OECD: Organisation for Economic Co-operation and Development
OECD (2023), Infrastructure investment (indicator). doi: 10.1787/b06ce3ad-en (Accessed on 17 December 2023)
https://data.oecd.org/transport/infrastructure-investment.htm

Infrastructure investment covers spending on new transport construction and the improvement of the existing network. Infrastructure investment is a key determinant of performance in the transport sector. Inland infrastructure includes road, rail, inland waterways, maritime ports and airports and takes account of all sources of financing. Efficient transport infrastructure provides economic and social benefits to both advanced and emerging economies by: improving market accessibility and productivity, ensuring balanced regional economic development, creating employment, promoting labour mobility and connecting communities. This indicator is measured as a share of GDP for total inland investment and in euros for the road, rail, air, inland waterways and sea components.


Definition of Infrastructure investment:

Infrastructure investment covers spending on new transport construction and the improvement of the existing network. Infrastructure investment is a key determinant of performance in the transport sector. Inland infrastructure includes road, rail, inland waterways, maritime ports and airports and takes account of all sources of financing. Efficient transport infrastructure provides economic and social benefits to both advanced and emerging economies by: improving market accessibility and productivity, ensuring balanced regional economic development, creating employment, promoting labour mobility and connecting communities. This indicator is measured as a share of GDP for total inland investment and in euros for the road, rail, air, inland waterways and sea components

     __________________________////__________________________________

#### Dataset 2: Passenger transport Rail / Road, Million passenger-kilometres, 2018 – 2021

Source: Passenger transport

https://data.oecd.org/transport/passenger-transport.htm#indicator-chart

Citation: OECD (2023), Passenger transport (indicator). doi: 10.1787/463da4d1-en (Accessed on 17 December 2023)

Passenger transport refers to the total movement of passengers using inland transport on a given network. Data are expressed in million passenger-kilometres, which represents the transport of a passenger for one kilometre. Components for road and rail are available.

Definition of Passenger transport:

Passenger transport refers to the total movement of passengers using inland transport on a given network. Data are expressed in million passenger-kilometres, which represents the transport of a passenger for one kilometre. Components for road and rail are available.

        ________________________________________////___________________________________________
        
#### Dataset 3: Passenger car registrations

https://data.oecd.org/transport/passenger-car-registrations.htm#indicator-chart

Passenger car registrations refer to the number of newly (first-time) registered passenger cars (private cars) or vehicles (commercial cars) registered to the authorities. Data are sourced via the European Automobile Manufacturer's Association (ACEA) and measured in number of units. Data are measured as an index with the base year 2015.

Definition of Passenger car registrations: 

Passenger car registrations refer to the number of newly (first-time) registered passenger cars (private cars) or vehicles (commercial cars) registered to the authorities. Data are sourced via the European Automobile Manufacturer's Association (ACEA) and measured in number of units. Data are measured as an index with the base year 2015.

Citation:
OECD (2023), Passenger car registrations (indicator). doi: 10.1787/c58fcf22-en (Accessed on 17 December 2023)

    _____________________________________________________////____________________________________________
   
#### Dataset 4 : Gross domestic product (GDP)

https://data.oecd.org/gdp/gross-domestic-product-gdp.htm#indicator-chart

Gross domestic product (GDP) is the standard measure of the value added created through the production of goods and services in a country during a certain period. As such, it also measures the income earned from that production, or the total amount spent on final goods and services (less imports). While GDP is the single most important indicator to capture economic activity, it falls short of providing a suitable measure of people's material well-being for which alternative indicators may be more appropriate. This indicator is based on nominal GDP (also called GDP at current prices or GDP in value) and is available in different measures: US dollars and US dollars per capita (current PPPs). All OECD countries compile their data according to the 2008 System of National Accounts (SNA). This indicator is less suited for comparisons over time, as developments are not only caused by real growth, but also by changes in prices and PPPs.

Definition of Gross domestic product (GDP):

Gross domestic product (GDP) is the standard measure of the value added created through the production of goods and services in a country during a certain period. As such, it also measures the income earned from that production, or the total amount spent on final goods and services (less imports). While GDP is the single most important indicator to capture economic activity, it falls short of providing a suitable measure of people's material well-being for which alternative indicators may be more appropriate. This indicator is based on nominal GDP (also called GDP at current prices or GDP in value) and is available in different measures: US dollars and US dollars per capita (current PPPs). All OECD countries compile their data according to the 2008 System of National Accounts (SNA). This indicator is less suited for comparisons over time, as developments are not only caused by real growth, but also by changes in prices and PPPs.

Citation:

OECD (2023), Gross domestic product (GDP) (indicator). doi: 10.1787/dc2f7aec-en (Accessed on 17 December 2023)

In [733]:
#Importing the essential libraries, which are Pandas, Matplotlib, Numpy, and Seaborn.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import style
from matplotlib import cm
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [734]:
#Command to display all columns in the file.
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#### Dataset - 1

In [735]:
# Importing the Dataset 
infra_invest_df= pd.read_csv('infra_invest_transport_rail_road.csv')
infra_invest_df.head()

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUS,INFRAINVEST,RAIL,EUR,A,2018,4.628355e+09,NaN
1,AUS,INFRAINVEST,RAIL,EUR,A,2019,4.935198e+09,NaN
2,AUS,INFRAINVEST,RAIL,EUR,A,2020,5.192725e+09,NaN
3,AUS,INFRAINVEST,RAIL,EUR,A,2021,6.750072e+09,NaN
4,AUS,INFRAINVEST,ROAD,EUR,A,2018,1.436391e+10,NaN

In [736]:
infra_invest_df.shape

(235, 8)

In [737]:
infra_invest_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    235 non-null    object
 1   INDICATOR   235 non-null    object
 2   SUBJECT     235 non-null    object
 3   MEASURE     235 non-null    object
 4   FREQUENCY   235 non-null    object
 5   TIME        235 non-null    int64
 6   Value       231 non-null    float64
 7   Flag Codes  21 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 14.8+ KB

In [738]:
infra_invest_df.dtypes

LOCATION       object
INDICATOR      object
SUBJECT        object
MEASURE        object
FREQUENCY      object
TIME            int64
Value         float64
Flag Codes     object
dtype: object

In [739]:
infra_invest_df.nunique()

LOCATION       35
INDICATOR       1
SUBJECT         2
MEASURE         1
FREQUENCY       1
TIME            4
Value         229
Flag Codes      3
dtype: int64

In [740]:
infra_invest_df.isnull().sum()

LOCATION        0
INDICATOR       0
SUBJECT         0
MEASURE         0
FREQUENCY       0
TIME            0
Value           4
Flag Codes    214
dtype: int64

In [741]:
# Identifying duplicates (Keep to False)
duplicates = infra_invest_df.duplicated(keep=False)
print('Duplicates rows:')
print(infra_invest_df[duplicates])

Duplicates rows:
Empty DataFrame
Columns: [LOCATION, INDICATOR, SUBJECT, MEASURE, FREQUENCY, TIME, Value, Flag Codes]
Index: []

In [742]:
infra_invest_df = infra_invest_df.drop(['Flag Codes', 'FREQUENCY'], axis=1)
infra_invest_df.head()

  LOCATION    INDICATOR SUBJECT MEASURE  TIME         Value
0      AUS  INFRAINVEST    RAIL     EUR  2018  4.628355e+09
1      AUS  INFRAINVEST    RAIL     EUR  2019  4.935198e+09
2      AUS  INFRAINVEST    RAIL     EUR  2020  5.192725e+09
3      AUS  INFRAINVEST    RAIL     EUR  2021  6.750072e+09
4      AUS  INFRAINVEST    ROAD     EUR  2018  1.436391e+10

In [743]:
infra_invest_df.isnull().values.any()

True

In [744]:
infra_invest_df.isnull().sum()

LOCATION     0
INDICATOR    0
SUBJECT      0
MEASURE      0
TIME         0
Value        4
dtype: int64

In [745]:
# Displaying only rows with missing values in 'Value' column 
missing_value_rows = infra_invest_df[infra_invest_df['Value'].isnull()]

print(missing_value_rows)

   LOCATION    INDICATOR SUBJECT MEASURE  TIME  Value
78      ISL  INFRAINVEST    RAIL     EUR  2018    NaN
79      ISL  INFRAINVEST    RAIL     EUR  2019    NaN
80      ISL  INFRAINVEST    RAIL     EUR  2020    NaN
81      ISL  INFRAINVEST    RAIL     EUR  2021    NaN

The missing values in the 'Value' column constitute approximately 1.70% of the total dataset. This is a relatively small percentage and occurs in locations that are not included in the study; in this situation, the simple method such as `dropna` will be used to deal with these missing values.

In [746]:
# Drop rows with missing values in the 'Value' column and rename the DataFrame
newinfra_invest_df = infra_invest_df.dropna(subset=['Value'])

# Display the new DataFrame
newinfra_invest_df.head(2)

  LOCATION    INDICATOR SUBJECT MEASURE  TIME         Value
0      AUS  INFRAINVEST    RAIL     EUR  2018  4.628355e+09
1      AUS  INFRAINVEST    RAIL     EUR  2019  4.935198e+09

In [747]:
newinfra_invest_df.shape

(231, 6)

In [748]:
newinfra_invest_df.isnull().values.any()

False

    ___________________________/////___________________________
#### Dataset - 2

In [749]:
# Importing the Dataset 
passenger_transport = pd.read_csv('passenger_transport.csv')
passenger_transport.head()

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2018,17157.920674,NaN
1,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2019,17814.174308,NaN
2,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2020,14166.446294,NaN
3,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2021,8845.193462,NaN
4,AUS,PASSTRANSP,ROAD,MLN_PKM,A,2018,304707.073631,NaN

In [750]:
passenger_transport.shape

(218, 8)

In [751]:
passenger_transport.isnull().sum()

LOCATION        0
INDICATOR       0
SUBJECT         0
MEASURE         0
FREQUENCY       0
TIME            0
Value           4
Flag Codes    191
dtype: int64

In [752]:
passenger_transport = passenger_transport.drop(['Flag Codes', 'FREQUENCY'], axis=1)
passenger_transport.head()

  LOCATION   INDICATOR SUBJECT  MEASURE  TIME          Value
0      AUS  PASSTRANSP    RAIL  MLN_PKM  2018   17157.920674
1      AUS  PASSTRANSP    RAIL  MLN_PKM  2019   17814.174308
2      AUS  PASSTRANSP    RAIL  MLN_PKM  2020   14166.446294
3      AUS  PASSTRANSP    RAIL  MLN_PKM  2021    8845.193462
4      AUS  PASSTRANSP    ROAD  MLN_PKM  2018  304707.073631

In [753]:
passenger_transport.shape

(218, 6)

In [754]:
passenger_transport.isnull().values.any()

True

In [755]:
passenger_transport.isnull().sum()

LOCATION     0
INDICATOR    0
SUBJECT      0
MEASURE      0
TIME         0
Value        4
dtype: int64

In [756]:
# Displaying only rows with missing values in 'Value' column 
missing_value_rows = passenger_transport[passenger_transport['Value'].isnull()]

print(missing_value_rows)

   LOCATION   INDICATOR SUBJECT  MEASURE  TIME  Value
65      ISL  PASSTRANSP    RAIL  MLN_PKM  2018    NaN
66      ISL  PASSTRANSP    RAIL  MLN_PKM  2019    NaN
67      ISL  PASSTRANSP    RAIL  MLN_PKM  2020    NaN
68      ISL  PASSTRANSP    RAIL  MLN_PKM  2021    NaN

The method `dropna` will be used to deal with these missing values for the same reason that the infra_invest_df dataset was justified.

In [757]:
# Drop rows with missing values in the 'Value' column and rename the DataFrame
newpassenger_transport = passenger_transport.dropna(subset=['Value'])

# Display the new DataFrame
newpassenger_transport.head(2)

  LOCATION   INDICATOR SUBJECT  MEASURE  TIME         Value
0      AUS  PASSTRANSP    RAIL  MLN_PKM  2018  17157.920674
1      AUS  PASSTRANSP    RAIL  MLN_PKM  2019  17814.174308

In [758]:
newpassenger_transport.isnull().values.any()

False

    ___________________________/////___________________________
#### Dataset - 3

In [759]:
# Importing the Dataset 
car_regist = pd.read_csv('passenger_car_registrations.csv')
car_regist.head()

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUS,PASSCAR,TOT,IDX2015,M,2015-01,92.612710,NaN
1,AUS,PASSCAR,TOT,IDX2015,M,2015-02,94.883872,NaN
2,AUS,PASSCAR,TOT,IDX2015,M,2015-03,112.127024,NaN
3,AUS,PASSCAR,TOT,IDX2015,M,2015-04,81.480289,NaN
4,AUS,PASSCAR,TOT,IDX2015,M,2015-05,94.458029,NaN

In [760]:
car_regist.shape

(2763, 8)

In [761]:
car_regist.isnull().sum()

LOCATION         0
INDICATOR        0
SUBJECT          0
MEASURE          0
FREQUENCY        0
TIME             0
Value            0
Flag Codes    2757
dtype: int64

In [762]:
car_regist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2763 entries, 0 to 2762
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    2763 non-null   object
 1   INDICATOR   2763 non-null   object
 2   SUBJECT     2763 non-null   object
 3   MEASURE     2763 non-null   object
 4   FREQUENCY   2763 non-null   object
 5   TIME        2763 non-null   object
 6   Value       2763 non-null   float64
 7   Flag Codes  6 non-null      object
dtypes: float64(1), object(7)
memory usage: 172.8+ KB

In [763]:
car_regist = car_regist.drop(['FREQUENCY', 'Flag Codes'], axis=1)
car_regist.head()

  LOCATION INDICATOR SUBJECT  MEASURE     TIME       Value
0      AUS   PASSCAR     TOT  IDX2015  2015-01   92.612710
1      AUS   PASSCAR     TOT  IDX2015  2015-02   94.883872
2      AUS   PASSCAR     TOT  IDX2015  2015-03  112.127024
3      AUS   PASSCAR     TOT  IDX2015  2015-04   81.480289
4      AUS   PASSCAR     TOT  IDX2015  2015-05   94.458029

In [764]:
# Extract the year from the 'TIME' column and convert it to int64
car_regist['TIME'] = car_regist['TIME'].str.split('-').str[0].astype('int64')

# Renaming the DataFrame
newcar_regist = car_regist

# Display the new DataFrame, where the 'TIME' column only contains the year as an integer
newcar_regist.head()

  LOCATION INDICATOR SUBJECT  MEASURE  TIME       Value
0      AUS   PASSCAR     TOT  IDX2015  2015   92.612710
1      AUS   PASSCAR     TOT  IDX2015  2015   94.883872
2      AUS   PASSCAR     TOT  IDX2015  2015  112.127024
3      AUS   PASSCAR     TOT  IDX2015  2015   81.480289
4      AUS   PASSCAR     TOT  IDX2015  2015   94.458029

The aggregation of passenger car registration data by averaging index values was chosen because it best reflects the annual trend of car registrations relative to the base year of 2015. This approach is consistent with traditional statistical practices and correlates with the indexed structure of the data by providing a clear, annual comparative indicator, which is critical for analysing year-over-year trends.

In [765]:
# Average the index 'Value' for each combination of 'LOCATION', 'INDICATOR', 'SUBJECT', 'MEASURE', and 'TIME'
newcar2_regist = newcar_regist.groupby(['LOCATION', 'INDICATOR', 'SUBJECT', 'MEASURE', 'TIME']).agg({'Value': 'mean'}).reset_index()

# Checking the aggregated data
newcar2_regist.head()

  LOCATION INDICATOR SUBJECT  MEASURE  TIME       Value
0      AUS   PASSCAR     TOT  IDX2015  2015  100.000000
1      AUS   PASSCAR     TOT  IDX2015  2016   94.293781
2      AUS   PASSCAR     TOT  IDX2015  2017   87.265239
3      AUS   PASSCAR     TOT  IDX2015  2018   73.393150
4      AUS   PASSCAR     TOT  IDX2015  2019   61.564372

In [766]:
newcar2_regist.dtypes

LOCATION      object
INDICATOR     object
SUBJECT       object
MEASURE       object
TIME           int64
Value        float64
dtype: object

In [767]:
newcar2_regist.shape

(231, 6)

In [768]:
newcar2_regist.isnull().values.any()

False

    ___________________________/////___________________________
#### Dataset - 4

In [769]:
# Importing the Dataset 
GDP_df= pd.read_csv('GDP_data.csv')
GDP_df.head()

  LOCATION INDICATOR SUBJECT  MEASURE FREQUENCY  TIME        Value Flag Codes
0      AUS       GDP     TOT  MLN_USD         A  2018  1326195.638        NaN
1      AUS       GDP     TOT  MLN_USD         A  2019  1341053.276        NaN
2      AUS       GDP     TOT  MLN_USD         A  2020  1436700.137        NaN
3      AUS       GDP     TOT  MLN_USD         A  2021  1611809.807        NaN
4      AUS       GDP     TOT  MLN_USD         A  2022  1804621.816        NaN

In [770]:
GDP_df.shape

(195, 8)

In [771]:
GDP_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    195 non-null    object
 1   INDICATOR   195 non-null    object
 2   SUBJECT     195 non-null    object
 3   MEASURE     195 non-null    object
 4   FREQUENCY   195 non-null    object
 5   TIME        195 non-null    int64
 6   Value       195 non-null    float64
 7   Flag Codes  32 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 12.3+ KB

In [772]:
GDP_df.isnull().sum()

LOCATION        0
INDICATOR       0
SUBJECT         0
MEASURE         0
FREQUENCY       0
TIME            0
Value           0
Flag Codes    163
dtype: int64

In [773]:
# Drop the columns and rename the DataFrame
newgdp_df = GDP_df.drop(['Flag Codes', 'FREQUENCY'], axis=1)
newgdp_df.head()

  LOCATION INDICATOR SUBJECT  MEASURE  TIME        Value
0      AUS       GDP     TOT  MLN_USD  2018  1326195.638
1      AUS       GDP     TOT  MLN_USD  2019  1341053.276
2      AUS       GDP     TOT  MLN_USD  2020  1436700.137
3      AUS       GDP     TOT  MLN_USD  2021  1611809.807
4      AUS       GDP     TOT  MLN_USD  2022  1804621.816

In [774]:
newgdp_df.shape

(195, 6)

In [775]:
newgdp_df.isnull().values.any()

False

The transformed dataset is now properly formatted for analytical purposes, or the datasets can be combined if necessary. The renaming, dropping, and reordering of columns, as well as the transformation of numerical month data into descriptive labels, improve the dataset's readability. This stage is critical in data analysis because it ensures that the dataset is in the best possible structure for extracting valuable insights and supporting effective data-driven decision-making processes in transportation research.

#### Display all the datasets after transformed

In [776]:
newinfra_invest_df.head(2)

  LOCATION    INDICATOR SUBJECT MEASURE  TIME         Value
0      AUS  INFRAINVEST    RAIL     EUR  2018  4.628355e+09
1      AUS  INFRAINVEST    RAIL     EUR  2019  4.935198e+09

In [777]:
newinfra_invest_df.shape

(231, 6)

In [778]:
newpassenger_transport.head(2)

  LOCATION   INDICATOR SUBJECT  MEASURE  TIME         Value
0      AUS  PASSTRANSP    RAIL  MLN_PKM  2018  17157.920674
1      AUS  PASSTRANSP    RAIL  MLN_PKM  2019  17814.174308

In [779]:
newpassenger_transport.shape

(214, 6)

In [780]:
newgdp_df.head(2)

  LOCATION INDICATOR SUBJECT  MEASURE  TIME        Value
0      AUS       GDP     TOT  MLN_USD  2018  1326195.638
1      AUS       GDP     TOT  MLN_USD  2019  1341053.276

In [781]:
newgdp_df.shape

(195, 6)

In [782]:
newcar2_regist.head(2)

  LOCATION INDICATOR SUBJECT  MEASURE  TIME       Value
0      AUS   PASSCAR     TOT  IDX2015  2015  100.000000
1      AUS   PASSCAR     TOT  IDX2015  2016   94.293781

In [783]:
newcar2_regist.shape

(231, 6)

The use of concatenation as a data combining method is consistent with the goal of maintaining data completeness, transparency, and flexibility throughout the research process. It ensures that all data points, including those that do not have matches across all databases, are considered, allowing for a thorough study and interpretation of the combined data.

In [784]:
# Concatenate all the datasets
combined_df = pd.concat([newinfra_invest_df, newpassenger_transport, newgdp_df, newcar2_regist])

# Check the final combined data
combined_df.tail()

    LOCATION INDICATOR SUBJECT  MEASURE  TIME      Value
226      USA   PASSCAR     TOT  IDX2015  2017  80.881982
227      USA   PASSCAR     TOT  IDX2015  2018  70.534635
228      USA   PASSCAR     TOT  IDX2015  2019  62.692435
229      USA   PASSCAR     TOT  IDX2015  2020  45.185628
230      USA   PASSCAR     TOT  IDX2015  2021  44.498904

In [785]:
combined_df.shape

(871, 6)

In [786]:
combined_df.isnull().values.any()

False

In [787]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 871 entries, 0 to 230
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LOCATION   871 non-null    object
 1   INDICATOR  871 non-null    object
 2   SUBJECT    871 non-null    object
 3   MEASURE    871 non-null    object
 4   TIME       871 non-null    int64
 5   Value      871 non-null    float64
dtypes: float64(1), int64(1), object(4)
memory usage: 47.6+ KB

In [788]:
combined_df.describe()

              TIME         Value
count   871.000000  8.710000e+02
mean   2019.169920  1.310489e+09
std       1.640315  6.827576e+09
min    2015.000000  4.296360e+01
25%    2018.000000  1.505959e+02
50%    2019.000000  1.879590e+05
75%    2020.000000  8.479500e+07
max    2022.000000  9.619507e+10

In [789]:
combined_df.nunique()

LOCATION      39
INDICATOR      4
SUBJECT        3
MEASURE        4
TIME           8
Value        850
dtype: int64

Create a Dictionary: First, create a dictionary that contains the mapping of country codes to country names. 

Automate the Mapping: Use this dictionary to replace the country codes in your dataset with their corresponding names.

# Dictionary for country code to name mapping
country_mapping = {
    'AUS': 'Australia', 'AUT': 'Austria', 'BEL': 'Belgium', 'CAN': 'Canada', 
    'CZE': 'Czech Republic', 'DNK': 'Denmark', 'FIN': 'Finland', 'FRA': 'France', 
    'DEU': 'Germany', 'GRC': 'Greece', 'HUN': 'Hungary', 'ISL': 'Iceland',
    'IRL': 'Ireland', 'ITA': 'Italy', 'JPN': 'Japan', 'KOR': 'South Korea', 
    'LUX': 'Luxembourg', 'MEX': 'Mexico', 'NZL': 'New Zealand', 'NOR': 'Norway', 
    'POL': 'Poland', 'PRT': 'Portugal', 'SVK': 'Slovakia', 'ESP': 'Spain',
    'SWE': 'Sweden', 'CHE': 'Switzerland', 'TUR': 'Turkey', 'GBR': 'United Kingdom', 
    'USA': 'United States', 'EST': 'Estonia', 'LVA': 'Latvia', 'LTU': 'Lithuania', 
    'SVN': 'Slovenia', 'ISR': 'Israel', 'CHL': 'Chile'
}

# Replace the country codes with names in the DataFrame
combined_df['LOCATION'] = combined_df['LOCATION'].map(country_mapping)

# Display the updated DataFrame
combined_df.head()