### MSC_DA_CA2

#### Main Dataset: THA25 - Passenger Journeys by Public Transport
        
https://data.gov.ie/dataset/tha25-passenger-journeys-by-public-transport
    
Published by: National Transport Authority
Licensed under: Creative Commons Attribution 4.0
Category: Transport   
    
Data Owner	Noreen Dorgan
Data Owner Email	transport@cso.ie
Data Owner Telephone	(+353) 21 453 5260
Theme	Transport
Date updated	2023-10-19
Language	English
Landing page	https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/THA25/JSON-stat/2.0/en
    
        ________________________________________////___________________________________________

### Compare: Ireland (IRL)  with New Zealand (NZL), Finland (FIN) or Norway (NOR), Denmark (DNK), Portugal (PRT). 

Ireland's transport infrastructure can be compared to those of other countries in a variety of ways. Here are a few nations that may provide useful comparisons with Ireland in terms of economic growth, size, geography, and urban-rural dynamics:

Consider aspects such as the extent and quality of road and rail networks, investment in public transport, policies towards sustainable transportation, and the difficulty of providing connectivity in both urban and rural areas when comparing Ireland's transport infrastructure to that of these countries. While these countries share certain qualities with Ireland, they also have distinct characteristics due to their varied geographical, economic, and historical circumstances.

#### Dataset 1 : Infrastructure investment Rail and Road / Euro, 2021 

Source: Transport infrastructure investment and maintenance

OECD: Organisation for Economic Co-operation and Development
OECD (2023), Infrastructure investment (indicator). doi: 10.1787/b06ce3ad-en (Accessed on 17 December 2023)
https://data.oecd.org/transport/infrastructure-investment.htm

Infrastructure investment covers spending on new transport construction and the improvement of the existing network. Infrastructure investment is a key determinant of performance in the transport sector. Inland infrastructure includes road, rail, inland waterways, maritime ports and airports and takes account of all sources of financing. Efficient transport infrastructure provides economic and social benefits to both advanced and emerging economies by: improving market accessibility and productivity, ensuring balanced regional economic development, creating employment, promoting labour mobility and connecting communities. This indicator is measured as a share of GDP for total inland investment and in euros for the road, rail, air, inland waterways and sea components.


Definition of Infrastructure investment:

Infrastructure investment covers spending on new transport construction and the improvement of the existing network. Infrastructure investment is a key determinant of performance in the transport sector. Inland infrastructure includes road, rail, inland waterways, maritime ports and airports and takes account of all sources of financing. Efficient transport infrastructure provides economic and social benefits to both advanced and emerging economies by: improving market accessibility and productivity, ensuring balanced regional economic development, creating employment, promoting labour mobility and connecting communities. This indicator is measured as a share of GDP for total inland investment and in euros for the road, rail, air, inland waterways and sea components

        ________________________________________////___________________________________________
      

#### Dataset 2: Passenger transport Rail / Road, Million passenger-kilometres, 2018 – 2021

Source: Passenger transport

https://data.oecd.org/transport/passenger-transport.htm#indicator-chart

Citation: OECD (2023), Passenger transport (indicator). doi: 10.1787/463da4d1-en (Accessed on 17 December 2023)

Passenger transport refers to the total movement of passengers using inland transport on a given network. Data are expressed in million passenger-kilometres, which represents the transport of a passenger for one kilometre. Components for road and rail are available.

Definition of Passenger transport:

Passenger transport refers to the total movement of passengers using inland transport on a given network. Data are expressed in million passenger-kilometres, which represents the transport of a passenger for one kilometre. Components for road and rail are available.

        ________________________________________////___________________________________________
      

 
#### Dataset 3: Gross domestic product (GDP)

https://data.oecd.org/gdp/gross-domestic-product-gdp.htm#indicator-chart

Gross domestic product (GDP) is the standard measure of the value added created through the production of goods and services in a country during a certain period. As such, it also measures the income earned from that production, or the total amount spent on final goods and services (less imports). While GDP is the single most important indicator to capture economic activity, it falls short of providing a suitable measure of people's material well-being for which alternative indicators may be more appropriate. This indicator is based on nominal GDP (also called GDP at current prices or GDP in value) and is available in different measures: US dollars and US dollars per capita (current PPPs). All OECD countries compile their data according to the 2008 System of National Accounts (SNA). This indicator is less suited for comparisons over time, as developments are not only caused by real growth, but also by changes in prices and PPPs.

Definition of Gross domestic product (GDP):

Gross domestic product (GDP) is the standard measure of the value added created through the production of goods and services in a country during a certain period. As such, it also measures the income earned from that production, or the total amount spent on final goods and services (less imports). While GDP is the single most important indicator to capture economic activity, it falls short of providing a suitable measure of people's material well-being for which alternative indicators may be more appropriate. This indicator is based on nominal GDP (also called GDP at current prices or GDP in value) and is available in different measures: US dollars and US dollars per capita (current PPPs). All OECD countries compile their data according to the 2008 System of National Accounts (SNA). This indicator is less suited for comparisons over time, as developments are not only caused by real growth, but also by changes in prices and PPPs.

Citation:

OECD (2023), Gross domestic product (GDP) (indicator). doi: 10.1787/dc2f7aec-en (Accessed on 17 December 2023)

In [1]:
#Importing the essential libraries, which are Pandas, Matplotlib, Numpy, and Seaborn.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import style
from matplotlib import cm
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
#Command to display all columns in the file.
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
# Importing the Dataset 
public_transp_ie = pd.read_csv('passenger_publictransp_ie.csv')
public_transp_ie.head()

,STATISTIC,Statistic Label,TLIST(W1),Week,C03935V04687,Mode of Transport,UNIT,VALUE
0,THA25C01,Passenger Journeys,2019W01,2019 Week 01,10,Dublin Metro Bus,Number,1987891.0
1,THA25C01,Passenger Journeys,2019W01,2019 Week 01,20,"Bus, excluding Dublin Metro",Number,497598.0
2,THA25C01,Passenger Journeys,2019W01,2019 Week 01,30,Rail,Number,NaN
3,THA25C01,Passenger Journeys,2019W01,2019 Week 01,40,"All public transport, excluding LUAS",Number,2485489.0
4,THA25C01,Passenger Journeys,2019W02,2019 Week 02,10,Dublin Metro Bus,Number,2709579.0

In [4]:
public_transp_ie.shape

(1024, 8)

In [5]:
public_transp_ie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1024 entries, 0 to 1023
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   STATISTIC          1024 non-null   object
 1   Statistic Label    1024 non-null   object
 2   TLIST(W1)          1024 non-null   object
 3   Week               1024 non-null   object
 4   C03935V04687       1024 non-null   int64
 5   Mode of Transport  1024 non-null   object
 6   UNIT               1024 non-null   object
 7   VALUE              960 non-null    float64
dtypes: float64(1), int64(1), object(6)
memory usage: 64.1+ KB

In [6]:
public_transp_ie.isnull().sum()

STATISTIC             0
Statistic Label       0
TLIST(W1)             0
Week                  0
C03935V04687          0
Mode of Transport     0
UNIT                  0
VALUE                64
dtype: int64

In [7]:
# Displaying only rows with missing values in 'Value' column 
missing_value_rows = public_transp_ie[public_transp_ie['VALUE'].isnull()]
print(missing_value_rows)

    STATISTIC     Statistic Label TLIST(W1)          Week  C03935V04687  \
2    THA25C01  Passenger Journeys   2019W01  2019 Week 01            30
6    THA25C01  Passenger Journeys   2019W02  2019 Week 02            30
10   THA25C01  Passenger Journeys   2019W03  2019 Week 03            30
14   THA25C01  Passenger Journeys   2019W04  2019 Week 04            30
18   THA25C01  Passenger Journeys   2019W05  2019 Week 05            30
22   THA25C01  Passenger Journeys   2019W06  2019 Week 06            30
26   THA25C01  Passenger Journeys   2019W07  2019 Week 07            30
30   THA25C01  Passenger Journeys   2019W08  2019 Week 08            30
34   THA25C01  Passenger Journeys   2019W09  2019 Week 09            30
38   THA25C01  Passenger Journeys   2019W10  2019 Week 10            30
42   THA25C01  Passenger Journeys   2019W11  2019 Week 11            30
46   THA25C01  Passenger Journeys   2019W12  2019 Week 12            30
50   THA25C01  Passenger Journeys   2019W13  2019 Week 13            30
54   THA25C01  Passenger Journeys   2019W14  2019 Week 14            30
58   THA25C01  Passenger Journeys   2019W15  2019 Week 15            30
62   THA25C01  Passenger Journeys   2019W16  2019 Week 16            30
66   THA25C01  Passenger Journeys   2019W17  2019 Week 17            30
70   THA25C01  Passenger Journeys   2019W18  2019 Week 18            30
74   THA25C01  Passenger Journeys   2019W19  2019 Week 19            30
78   THA25C01  Passenger Journeys   2019W20  2019 Week 20            30
82   THA25C01  Passenger Journeys   2019W21  2019 Week 21            30
86   THA25C01  Passenger Journeys   2019W22  2019 Week 22            30
90   THA25C01  Passenger Journeys   2019W23  2019 Week 23            30
94   THA25C01  Passenger Journeys   2019W24  2019 Week 24            30
98   THA25C01  Passenger Journeys   2019W25  2019 Week 25            30
102  THA25C01  Passenger Journeys   2019W26  2019 Week 26            30
106  THA25C01  Passenger Journeys   2019W27  2019 Week 27            30
110  THA25C01  Passenger Journeys   2019W28  2019 Week 28            30
114  THA25C01  Passenger Journeys   2019W29  2019 Week 29            30
118  THA25C01  Passenger Journeys   2019W30  2019 Week 30            30
122  THA25C01  Passenger Journeys   2019W31  2019 Week 31            30
126  THA25C01  Passenger Journeys   2019W32  2019 Week 32            30
130  THA25C01  Passenger Journeys   2019W33  2019 Week 33            30
134  THA25C01  Passenger Journeys   2019W34  2019 Week 34            30
138  THA25C01  Passenger Journeys   2019W35  2019 Week 35            30
142  THA25C01  Passenger Journeys   2019W36  2019 Week 36            30
146  THA25C01  Passenger Journeys   2019W37  2019 Week 37            30
150  THA25C01  Passenger Journeys   2019W38  2019 Week 38            30
154  THA25C01  Passenger Journeys   2019W39  2019 Week 39            30
158  THA25C01  Passenger Journeys   2019W40  2019 Week 40            30
162  THA25C01  Passenger Journeys   2019W41  2019 Week 41            30
166  THA25C01  Passenger Journeys   2019W42  2019 Week 42            30
170  THA25C01  Passenger Journeys   2019W43  2019 Week 43            30
174  THA25C01  Passenger Journeys   2019W44  2019 Week 44            30
178  THA25C01  Passenger Journeys   2019W45  2019 Week 45            30
182  THA25C01  Passenger Journeys   2019W46  2019 Week 46            30
186  THA25C01  Passenger Journeys   2019W47  2019 Week 47            30
190  THA25C01  Passenger Journeys   2019W48  2019 Week 48            30
194  THA25C01  Passenger Journeys   2019W49  2019 Week 49            30
198  THA25C01  Passenger Journeys   2019W50  2019 Week 50            30
202  THA25C01  Passenger Journeys   2019W51  2019 Week 51            30
206  THA25C01  Passenger Journeys   2019W52  2019 Week 52            30
208  THA25C01  Passenger Journeys   2019W53  2019 Week 53            10
209  THA25C01  Passenger Journeys   2019W53  2019 Week 53            20
210  THA25C01  Passenger Journeys   2019W53  2019 Week 53            30
211  THA25C01  Passenger Journeys   2019W53  2019 Week 53            40
632  THA25C01  Passenger Journeys   2021W53  2021 Week 53            10
633  THA25C01  Passenger Journeys   2021W53  2021 Week 53            20
634  THA25C01  Passenger Journeys   2021W53  2021 Week 53            30
635  THA25C01  Passenger Journeys   2021W53  2021 Week 53            40
844  THA25C01  Passenger Journeys   2022W53  2022 Week 53            10
845  THA25C01  Passenger Journeys   2022W53  2022 Week 53            20
846  THA25C01  Passenger Journeys   2022W53  2022 Week 53            30
847  THA25C01  Passenger Journeys   2022W53  2022 Week 53            40

                        Mode of Transport    UNIT  VALUE
2                                    Rail  Number    NaN
6                                    Rail  Number    NaN
10                                   Rail  Number    NaN
14                                   Rail  Number    NaN
18                                   Rail  Number    NaN
22                                   Rail  Number    NaN
26                                   Rail  Number    NaN
30                                   Rail  Number    NaN
34                                   Rail  Number    NaN
38                                   Rail  Number    NaN
42                                   Rail  Number    NaN
46                                   Rail  Number    NaN
50                                   Rail  Number    NaN
54                                   Rail  Number    NaN
58                                   Rail  Number    NaN
62                                   Rail  Number    NaN
66                                   Rail  Number    NaN
70                                   Rail  Number    NaN
74                                   Rail  Number    NaN
78                                   Rail  Number    NaN
82                                   Rail  Number    NaN
86                                   Rail  Number    NaN
90                                   Rail  Number    NaN
94                                   Rail  Number    NaN
98                                   Rail  Number    NaN
102                                  Rail  Number    NaN
106                                  Rail  Number    NaN
110                                  Rail  Number    NaN
114                                  Rail  Number    NaN
118                                  Rail  Number    NaN
122                                  Rail  Number    NaN
126                                  Rail  Number    NaN
130                                  Rail  Number    NaN
134                                  Rail  Number    NaN
138                                  Rail  Number    NaN
142                                  Rail  Number    NaN
146                                  Rail  Number    NaN
150                                  Rail  Number    NaN
154                                  Rail  Number    NaN
158                                  Rail  Number    NaN
162                                  Rail  Number    NaN
166                                  Rail  Number    NaN
170                                  Rail  Number    NaN
174                                  Rail  Number    NaN
178                                  Rail  Number    NaN
182                                  Rail  Number    NaN
186                                  Rail  Number    NaN
190                                  Rail  Number    NaN
194                                  Rail  Number    NaN
198                                  Rail  Number    NaN
202                                  Rail  Number    NaN
206                                  Rail  Number    NaN
208                      Dublin Metro Bus  Number    NaN
209           Bus, excluding Dublin Metro  Number    NaN
210                                  Rail  Number    NaN
211  All public transport, excluding LUAS  Number    NaN
632                      Dublin Metro Bus  Number    NaN
633           Bus, excluding Dublin Metro  Number    NaN
634                                  Rail  Number    NaN
635  All public transport, excluding LUAS  Number    NaN
844                      Dublin Metro Bus  Number    NaN
845           Bus, excluding Dublin Metro  Number    NaN
846                                  Rail  Number    NaN
847  All public transport, excluding LUAS  Number    NaN

In [8]:
public_transp_ie.describe()

       C03935V04687         VALUE
count   1024.000000  9.600000e+02
mean      25.000000  1.740812e+06
std       11.185803  1.423490e+06
min       10.000000  2.323100e+04
25%       17.500000  6.121042e+05
50%       25.000000  9.495040e+05
75%       32.500000  2.982254e+06
max       40.000000  5.488658e+06

In [9]:
# Convert 'Week' to 'year' and 'week_number'
public_transp_ie['year'] = public_transp_ie['Week'].apply(lambda x: int(x.split()[0]))
public_transp_ie['week_number'] = public_transp_ie['Week'].apply(lambda x: int(x.split()[2]))

public_transp_ie.head(2)

,STATISTIC,Statistic Label,TLIST(W1),Week,C03935V04687,Mode of Transport,UNIT,VALUE,year,week_number
0,THA25C01,Passenger Journeys,2019W01,2019 Week 01,10,Dublin Metro Bus,Number,1987891.0,2019,1
1,THA25C01,Passenger Journeys,2019W01,2019 Week 01,20,"Bus, excluding Dublin Metro",Number,497598.0,2019,1

The fill_missing_values_from_years function was defined to automate the process of imputation. and the function extracts the subset of data matching to each year given in fill_years. It looks through the fill_years for a corresponding value for each missing value. The basis for this correspondence is that the week number and mode of transportation must coincide.
The missing value is changed to this value if a matched value is discovered.

The column name C03935V04687 in the dataset represents the "Mode of Transport," where various means of transport such as "Dublin Metro Bus," "Bus, excluding Dublin Metro," and "Rail" are noted.
The 'C03935V04687' column is used to ensure that when missing values are filled, the data is correctly matched based on the mode of transmission. This is significant since the goal is to replace missing values with data from the same week in 2022, as well as the same mode of transportation.
For example, if a value is missing in 2019 for "Rail," the goal is to locate the value from 2022 for "Rail" in the same week, not for "Bus" or any other mode of transportation.

In [10]:
#Filling Missing Values
def fill_missing_values_from_years(df, missing_year, fill_years):
    for fill_year in fill_years:
        # Extract data for the fill year
        year_data = df[df['year'] == fill_year]

        # Iterate over the missing values in the specified year
        for index, row in df[(df['year'] == missing_year) & (df['VALUE'].isna())].iterrows():
            # Find the corresponding week's data in the fill year
            fill_value = year_data[(year_data['week_number'] == row['week_number']) & 
                                   (year_data['C03935V04687'] == row['C03935V04687'])]['VALUE']

            # Fill the missing value if a corresponding value is found
            if not fill_value.empty:
                df.at[index, 'VALUE'] = fill_value.values[0]

# Fill missing values for 2019 from 2022 and 2023
fill_missing_values_from_years(public_transp_ie, 2019, [2022, 2023])
public_transp_ie.isnull().sum()

STATISTIC             0
Statistic Label       0
TLIST(W1)             0
Week                  0
C03935V04687          0
Mode of Transport     0
UNIT                  0
VALUE                12
year                  0
week_number           0
dtype: int64

In [11]:
public_transp_ie.shape

(1024, 10)

There are remaining missing values after the imputation process that indicate for some weeks in 2019,, there were no equivalent data points in 2022 or 2023. There are several potential causes for this circumstance to occur. However, as the missing values make up a relatively small percentage (about 1.17%) of the dataset, the decision was made to dropped them. A small percentage of the data being excluded from a big dataset is unlikely to have an impact on the results' statistical significance. Conclusions from the analysis would probably be the same with or without these data points.

#### Drop the rows with missing values and rename the DataFrame; the result of the dropna() function can be assigned to a new DataFrame name.

In [12]:
public2_transp_ie = public_transp_ie.dropna(subset=['VALUE'])
public2_transp_ie.head(2)

,STATISTIC,Statistic Label,TLIST(W1),Week,C03935V04687,Mode of Transport,UNIT,VALUE,year,week_number
0,THA25C01,Passenger Journeys,2019W01,2019 Week 01,10,Dublin Metro Bus,Number,1987891.0,2019,1
1,THA25C01,Passenger Journeys,2019W01,2019 Week 01,20,"Bus, excluding Dublin Metro",Number,497598.0,2019,1

In [13]:
public2_transp_ie.isnull().values.any()

False

In [14]:
# Identifying duplicates (Keep to False)
duplicates = public_transp_ie.duplicated(keep=False)
print('Duplicates rows:')
print(public_transp_ie[duplicates])

Duplicates rows:
Empty DataFrame
Columns: [STATISTIC, Statistic Label, TLIST(W1), Week, C03935V04687, Mode of Transport, UNIT, VALUE, year, week_number]
Index: []

    ___________________________/////___________________________
#### Dataset - 2

In [79]:
# Importing the Dataset 
infra_invest_df= pd.read_csv('infra_invest_transport_rail_road.csv')
infra_invest_df.head()

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUS,INFRAINVEST,RAIL,EUR,A,2018,4.628355e+09,NaN
1,AUS,INFRAINVEST,RAIL,EUR,A,2019,4.935198e+09,NaN
2,AUS,INFRAINVEST,RAIL,EUR,A,2020,5.192725e+09,NaN
3,AUS,INFRAINVEST,RAIL,EUR,A,2021,6.750072e+09,NaN
4,AUS,INFRAINVEST,ROAD,EUR,A,2018,1.436391e+10,NaN

In [80]:
infra_invest_df.shape

(235, 8)

In [81]:
infra_invest_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    235 non-null    object
 1   INDICATOR   235 non-null    object
 2   SUBJECT     235 non-null    object
 3   MEASURE     235 non-null    object
 4   FREQUENCY   235 non-null    object
 5   TIME        235 non-null    int64
 6   Value       231 non-null    float64
 7   Flag Codes  21 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 14.8+ KB

In [82]:
infra_invest_df.dtypes

LOCATION       object
INDICATOR      object
SUBJECT        object
MEASURE        object
FREQUENCY      object
TIME            int64
Value         float64
Flag Codes     object
dtype: object

In [83]:
infra_invest_df.nunique()

LOCATION       35
INDICATOR       1
SUBJECT         2
MEASURE         1
FREQUENCY       1
TIME            4
Value         229
Flag Codes      3
dtype: int64

In [84]:
infra_invest_df.isnull().sum()

LOCATION        0
INDICATOR       0
SUBJECT         0
MEASURE         0
FREQUENCY       0
TIME            0
Value           4
Flag Codes    214
dtype: int64

In [85]:
# Identifying duplicates (Keep to False)
duplicates = infra_invest_df.duplicated(keep=False)
print('Duplicates rows:')
print(infra_invest_df[duplicates])

Duplicates rows:
Empty DataFrame
Columns: [LOCATION, INDICATOR, SUBJECT, MEASURE, FREQUENCY, TIME, Value, Flag Codes]
Index: []

In [86]:
# Drop the columns
infra_invest_df = infra_invest_df.drop(['Flag Codes', 'FREQUENCY'], axis=1)

# Rename columns
infra_invest_df = infra_invest_df.rename(columns={'LOCATION': 'COUNTRY', 'TIME': 'YEAR', 'Value': 'VALUE_INFRAINVEST'})

infra_invest_df.head()

  COUNTRY    INDICATOR SUBJECT MEASURE  YEAR  VALUE_INFRAINVEST
0     AUS  INFRAINVEST    RAIL     EUR  2018       4.628355e+09
1     AUS  INFRAINVEST    RAIL     EUR  2019       4.935198e+09
2     AUS  INFRAINVEST    RAIL     EUR  2020       5.192725e+09
3     AUS  INFRAINVEST    RAIL     EUR  2021       6.750072e+09
4     AUS  INFRAINVEST    ROAD     EUR  2018       1.436391e+10

In [87]:
infra_invest_df.isnull().values.any()

True

In [88]:
infra_invest_df.isnull().sum()

COUNTRY              0
INDICATOR            0
SUBJECT              0
MEASURE              0
YEAR                 0
VALUE_INFRAINVEST    4
dtype: int64

In [89]:
# Displaying only rows with missing values in 'Value' column 
missing_value_rows = infra_invest_df[infra_invest_df['VALUE_INFRAINVEST'].isnull()]

print(missing_value_rows)

   COUNTRY    INDICATOR SUBJECT MEASURE  YEAR  VALUE_INFRAINVEST
78     ISL  INFRAINVEST    RAIL     EUR  2018                NaN
79     ISL  INFRAINVEST    RAIL     EUR  2019                NaN
80     ISL  INFRAINVEST    RAIL     EUR  2020                NaN
81     ISL  INFRAINVEST    RAIL     EUR  2021                NaN

The missing values in the 'Value' column constitute approximately 1.70% of the total dataset. This is a relatively small percentage and occurs in locations that are not included in the study; in this situation, the simple method such as `dropna` will be used to deal with these missing values.

In [90]:
# Drop rows with missing values in the 'Value' column and rename the DataFrame
newinfra_invest_df = infra_invest_df.dropna(subset=['VALUE_INFRAINVEST'])

# Display the new DataFrame
newinfra_invest_df.head(2)

  COUNTRY    INDICATOR SUBJECT MEASURE  YEAR  VALUE_INFRAINVEST
0     AUS  INFRAINVEST    RAIL     EUR  2018       4.628355e+09
1     AUS  INFRAINVEST    RAIL     EUR  2019       4.935198e+09

In [91]:
newinfra_invest_df.shape

(231, 6)

In [92]:
newinfra_invest_df.isnull().values.any()

False

    ___________________________/////___________________________
#### Dataset - 3

In [93]:
# Importing the Dataset 
passenger_transp = pd.read_csv('passenger_transport.csv')
passenger_transp.head()

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2018,17157.920674,NaN
1,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2019,17814.174308,NaN
2,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2020,14166.446294,NaN
3,AUS,PASSTRANSP,RAIL,MLN_PKM,A,2021,8845.193462,NaN
4,AUS,PASSTRANSP,ROAD,MLN_PKM,A,2018,304707.073631,NaN

In [94]:
passenger_transp.shape

(218, 8)

In [95]:
passenger_transp.isnull().sum()

LOCATION        0
INDICATOR       0
SUBJECT         0
MEASURE         0
FREQUENCY       0
TIME            0
Value           4
Flag Codes    191
dtype: int64

In [96]:
# Drop Columns
passenger_transp = passenger_transp.drop(['Flag Codes', 'FREQUENCY'], axis=1)

# Rename columns
passenger_transp = passenger_transp.rename(columns={'LOCATION': 'COUNTRY', 'TIME': 'YEAR', 'Value': 'VALUE_PASSTRANSP'})

passenger_transp.head()

  COUNTRY   INDICATOR SUBJECT  MEASURE  YEAR  VALUE_PASSTRANSP
0     AUS  PASSTRANSP    RAIL  MLN_PKM  2018      17157.920674
1     AUS  PASSTRANSP    RAIL  MLN_PKM  2019      17814.174308
2     AUS  PASSTRANSP    RAIL  MLN_PKM  2020      14166.446294
3     AUS  PASSTRANSP    RAIL  MLN_PKM  2021       8845.193462
4     AUS  PASSTRANSP    ROAD  MLN_PKM  2018     304707.073631

In [97]:
passenger_transp.shape

(218, 6)

In [98]:
passenger_transp.isnull().values.any()

True

In [99]:
passenger_transp.isnull().sum()

COUNTRY             0
INDICATOR           0
SUBJECT             0
MEASURE             0
YEAR                0
VALUE_PASSTRANSP    4
dtype: int64

In [100]:
# Displaying only rows with missing values in 'Value' column 
missing_value_rows = passenger_transp[passenger_transp['VALUE_PASSTRANSP'].isnull()]

print(missing_value_rows)

   COUNTRY   INDICATOR SUBJECT  MEASURE  YEAR  VALUE_PASSTRANSP
65     ISL  PASSTRANSP    RAIL  MLN_PKM  2018               NaN
66     ISL  PASSTRANSP    RAIL  MLN_PKM  2019               NaN
67     ISL  PASSTRANSP    RAIL  MLN_PKM  2020               NaN
68     ISL  PASSTRANSP    RAIL  MLN_PKM  2021               NaN

The method `dropna` will be used to deal with these missing values for the same reason that the infra_invest_df dataset was justified.

In [101]:
# Drop rows with missing values in the 'Value' column and rename the DataFrame
newpassenger_transp = passenger_transp.dropna(subset=['VALUE_PASSTRANSP'])

# Display the new DataFrame
newpassenger_transp.head(2)

  COUNTRY   INDICATOR SUBJECT  MEASURE  YEAR  VALUE_PASSTRANSP
0     AUS  PASSTRANSP    RAIL  MLN_PKM  2018      17157.920674
1     AUS  PASSTRANSP    RAIL  MLN_PKM  2019      17814.174308

In [102]:
newpassenger_transp.isnull().values.any()

False

The aggregation of passenger car registration data by averaging index values was chosen because it best reflects the annual trend of car registrations relative to the base year of 2015. This approach is consistent with traditional statistical practices and correlates with the indexed structure of the data by providing a clear, annual comparative indicator, which is critical for analysing year-over-year trends.

    ___________________________/////___________________________
#### Dataset - 3

In [113]:
# Importing the Dataset 
GDP_df= pd.read_csv('GDP_data.csv')
GDP_df.head()

  LOCATION INDICATOR SUBJECT  MEASURE FREQUENCY  TIME        Value Flag Codes
0      AUS       GDP     TOT  MLN_USD         A  2018  1326195.638        NaN
1      AUS       GDP     TOT  MLN_USD         A  2019  1341053.276        NaN
2      AUS       GDP     TOT  MLN_USD         A  2020  1436700.137        NaN
3      AUS       GDP     TOT  MLN_USD         A  2021  1611809.807        NaN
4      AUS       GDP     TOT  MLN_USD         A  2022  1804621.816        NaN

In [114]:
GDP_df.shape

(195, 8)

In [115]:
GDP_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    195 non-null    object
 1   INDICATOR   195 non-null    object
 2   SUBJECT     195 non-null    object
 3   MEASURE     195 non-null    object
 4   FREQUENCY   195 non-null    object
 5   TIME        195 non-null    int64
 6   Value       195 non-null    float64
 7   Flag Codes  32 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 12.3+ KB

In [116]:
GDP_df.isnull().sum()

LOCATION        0
INDICATOR       0
SUBJECT         0
MEASURE         0
FREQUENCY       0
TIME            0
Value           0
Flag Codes    163
dtype: int64

In [117]:
# Drop the columns and rename the DataFrame
newgdp_df = GDP_df.drop(['Flag Codes', 'FREQUENCY'], axis=1)

# Rename columns
newgdp_df = newgdp_df.rename(columns={'LOCATION': 'COUNTRY', 'TIME': 'YEAR', 'Value': 'VALUE_GDP'})

newgdp_df.head()

  COUNTRY INDICATOR SUBJECT  MEASURE  YEAR    VALUE_GDP
0     AUS       GDP     TOT  MLN_USD  2018  1326195.638
1     AUS       GDP     TOT  MLN_USD  2019  1341053.276
2     AUS       GDP     TOT  MLN_USD  2020  1436700.137
3     AUS       GDP     TOT  MLN_USD  2021  1611809.807
4     AUS       GDP     TOT  MLN_USD  2022  1804621.816

In [118]:
newgdp_df.shape

(195, 6)

In [119]:
newgdp_df.isnull().values.any()

False

The transformed dataset is now properly formatted for analytical purposes, or the datasets can be combined if necessary. The renaming, dropping, and reordering of columns, as well as the transformation of numerical month data into descriptive labels, improve the dataset's readability. This stage is critical in data analysis because it ensures that the dataset is in the best possible structure for extracting valuable insights and supporting effective data-driven decision-making processes in transportation research.

#### Display the datasets (2, 3 and 4) after transformed

In [120]:
newinfra_invest_df.head(2)

  COUNTRY    INDICATOR SUBJECT MEASURE  YEAR  VALUE_INFRAINVEST
0     AUS  INFRAINVEST    RAIL     EUR  2018       4.628355e+09
1     AUS  INFRAINVEST    RAIL     EUR  2019       4.935198e+09

In [121]:
newinfra_invest_df.shape

(231, 6)

In [122]:
newinfra_invest_df.dtypes

COUNTRY               object
INDICATOR             object
SUBJECT               object
MEASURE               object
YEAR                   int64
VALUE_INFRAINVEST    float64
dtype: object

In [123]:
newpassenger_transp.head(2)

  COUNTRY   INDICATOR SUBJECT  MEASURE  YEAR  VALUE_PASSTRANSP
0     AUS  PASSTRANSP    RAIL  MLN_PKM  2018      17157.920674
1     AUS  PASSTRANSP    RAIL  MLN_PKM  2019      17814.174308

In [124]:
newpassenger_transp.shape

(214, 6)

In [125]:
newpassenger_transp.dtypes

COUNTRY              object
INDICATOR            object
SUBJECT              object
MEASURE              object
YEAR                  int64
VALUE_PASSTRANSP    float64
dtype: object

In [126]:
newgdp_df.head(2)

  COUNTRY INDICATOR SUBJECT  MEASURE  YEAR    VALUE_GDP
0     AUS       GDP     TOT  MLN_USD  2018  1326195.638
1     AUS       GDP     TOT  MLN_USD  2019  1341053.276

In [127]:
newgdp_df.shape

(195, 6)

In [128]:
newcar2_regist.head(2)

  COUNTRY INDICATOR SUBJECT  MEASURE  YEAR  VALUE_PASSCAR
0     AUS   PASSCAR     TOT  IDX2015  2015     100.000000
1     AUS   PASSCAR     TOT  IDX2015  2016      94.293781

In [129]:
newcar2_regist.shape

(231, 6)

#### Merging the DataFrames 2 AND 3

Given that the datasets 'infra_invest' and 'passenger_transport' include the identical observations for the 'COUNTRY' and 'YEAR' columns, a more precise merge utilising these two keys was performed. This method will align the data more properly and avoid missing values. Because the datasets 2 and 3 have comparable columns and observations, they were joined using the procedure `on how=left`. The merging technique `on how=outer` was tested with the key columns COUNTRY', 'YEAR', and 'SUBJECT', however the outputs had too many missing data.

In [130]:
# Merging the DataFrames on 'COUNTRY' and 'YEAR'
combined_df = pd.merge(newinfra_invest_df, newpassenger_transp, on=['COUNTRY', 'YEAR',], how='left')

# Display the first few rows of the combined DataFrame
combined_df.head(2)

,COUNTRY,INDICATOR_x,SUBJECT_x,MEASURE_x,YEAR,VALUE_INFRAINVEST,INDICATOR_y,SUBJECT_y,MEASURE_y,VALUE_PASSTRANSP
0,AUS,INFRAINVEST,RAIL,EUR,2018,4.628355e+09,PASSTRANSP,RAIL,MLN_PKM,17157.920674
1,AUS,INFRAINVEST,RAIL,EUR,2018,4.628355e+09,PASSTRANSP,ROAD,MLN_PKM,304707.073631

In [131]:
combined_df.shape

(363, 10)

In [132]:
combined_df.isnull().values.any()

False

In [133]:
# Rename columns and DataFrame
infrainvest_passtransp_df = combined_df .rename(columns={'INDICATOR_x': 'INDIC_INFRAINVEST', 'SUBJECT_x': 'SUBJECT_INFRA', 'MEASURE_x': 'VALUE_EUR',
                                                         'INDICATOR_y': 'INDIC_PASSTRANSP', 'SUBJECT_y': 'SUBJECT_PASSTRANSP','MEASURE_y':'MEASURE_PKM'})

# Remove the 'YEAR' column and store it
year_column = infrainvest_passtransp_df.pop('YEAR')

# Insert the 'YEAR' column back in the DataFrame after the 'COUNTRY' column
infrainvest_passtransp_df.insert(1, 'YEAR', year_column)

#Dysplay the Dataset
infrainvest_passtransp_df.head(2)

,COUNTRY,YEAR,INDIC_INFRAINVEST,SUBJECT_INFRA,VALUE_EUR,VALUE_INFRAINVEST,INDIC_PASSTRANSP,SUBJECT_PASSTRANSP,MEASURE_PKM,VALUE_PASSTRANSP
0,AUS,2018,INFRAINVEST,RAIL,EUR,4.628355e+09,PASSTRANSP,RAIL,MLN_PKM,17157.920674
1,AUS,2018,INFRAINVEST,RAIL,EUR,4.628355e+09,PASSTRANSP,ROAD,MLN_PKM,304707.073631

In [134]:
infrainvest_passtransp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 363 entries, 0 to 362
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   COUNTRY             363 non-null    object
 1   YEAR                363 non-null    int64
 2   INDIC_INFRAINVEST   363 non-null    object
 3   SUBJECT_INFRA       363 non-null    object
 4   VALUE_EUR           363 non-null    object
 5   VALUE_INFRAINVEST   363 non-null    float64
 6   INDIC_PASSTRANSP    363 non-null    object
 7   SUBJECT_PASSTRANSP  363 non-null    object
 8   MEASURE_PKM         363 non-null    object
 9   VALUE_PASSTRANSP    363 non-null    float64
dtypes: float64(2), int64(1), object(7)
memory usage: 28.5+ KB

In [135]:
infrainvest_passtransp_df.nunique()

COUNTRY                35
YEAR                    4
INDIC_INFRAINVEST       1
SUBJECT_INFRA           2
VALUE_EUR               1
VALUE_INFRAINVEST     229
INDIC_PASSTRANSP        1
SUBJECT_PASSTRANSP      2
MEASURE_PKM             1
VALUE_PASSTRANSP      192
dtype: int64

In [136]:
infrainvest_passtransp_df.describe()

              YEAR  VALUE_INFRAINVEST  VALUE_PASSTRANSP
count   363.000000       3.630000e+02      3.630000e+02
mean   2019.344353       6.072274e+09      2.683691e+05
std       1.099920       1.395871e+10      9.382580e+05
min    2018.000000       2.090000e+07      2.600000e+02
25%    2018.000000       6.838300e+08      3.627950e+03
50%    2019.000000       2.002000e+09      2.061300e+04
75%    2020.000000       6.278663e+09      1.043312e+05
max    2021.000000       9.619507e+10      6.674065e+06

#### Merging the DataFrames (2,3 and 4)

In [146]:
# Merging datasets on 'COUNTRY' and 'YEAR'
combined2_df = pd.merge(infrainvest_passtransp_df, newgdp_df, on=['COUNTRY', 'YEAR'], how='left')

combined2_df.head(2)

,COUNTRY,YEAR,INDIC_INFRAINVEST,SUBJECT_INFRA,VALUE_EUR,VALUE_INFRAINVEST,INDIC_PASSTRANSP,SUBJECT_PASSTRANSP,MEASURE_PKM,VALUE_PASSTRANSP,INDICATOR,SUBJECT,MEASURE,VALUE_GDP
0,AUS,2018,INFRAINVEST,RAIL,EUR,4.628355e+09,PASSTRANSP,RAIL,MLN_PKM,17157.920674,GDP,TOT,MLN_USD,1326195.638
1,AUS,2018,INFRAINVEST,RAIL,EUR,4.628355e+09,PASSTRANSP,ROAD,MLN_PKM,304707.073631,GDP,TOT,MLN_USD,1326195.638

#### Check for missing values after merging

In [142]:
combined2_df.isnull().values.any()

False

In [143]:
missing_values = combined2_df.isnull().sum()
print(missing_values)

COUNTRY               0
YEAR                  0
INDIC_INFRAINVEST     0
SUBJECT_INFRA         0
VALUE_EUR             0
VALUE_INFRAINVEST     0
INDIC_PASSTRANSP      0
SUBJECT_PASSTRANSP    0
MEASURE_PKM           0
VALUE_PASSTRANSP      0
INDICATOR             0
SUBJECT               0
MEASURE               0
VALUE_GDP             0
dtype: int64

In [144]:
combined2_df.shape

(363, 14)

The use of concatenation as a data combining method is consistent with the goal of maintaining data completeness, transparency, and flexibility throughout the research process. It ensures that all data points, including those that do not have matches across all databases, are considered, allowing for a thorough study and interpretation of the combined data.

Create a Dictionary: First, create a dictionary that contains the mapping of country codes to country names. 
Automate the Mapping: Use this dictionary to replace the country codes in your dataset with their corresponding names.

# Dictionary for country code to name mapping
country_mapping = {
    'AUS': 'Australia', 'AUT': 'Austria', 'BEL': 'Belgium', 'CAN': 'Canada', 
    'CZE': 'Czech Republic', 'DNK': 'Denmark', 'FIN': 'Finland', 'FRA': 'France', 
    'DEU': 'Germany', 'GRC': 'Greece', 'HUN': 'Hungary', 'ISL': 'Iceland',
    'IRL': 'Ireland', 'ITA': 'Italy', 'JPN': 'Japan', 'KOR': 'South Korea', 
    'LUX': 'Luxembourg', 'MEX': 'Mexico', 'NZL': 'New Zealand', 'NOR': 'Norway', 
    'POL': 'Poland', 'PRT': 'Portugal', 'SVK': 'Slovakia', 'ESP': 'Spain',
    'SWE': 'Sweden', 'CHE': 'Switzerland', 'TUR': 'Turkey', 'GBR': 'United Kingdom', 
    'USA': 'United States', 'EST': 'Estonia', 'LVA': 'Latvia', 'LTU': 'Lithuania', 
    'SVN': 'Slovenia', 'ISR': 'Israel', 'CHL': 'Chile'
}

# Replace the country codes with names in the DataFrame
combined_df['LOCATION'] = combined_df['LOCATION'].map(country_mapping)

# Display the updated DataFrame
combined_df.head()